'use strict';
/** @namespace DevKit */
var DevKit;
(function (DevKit) {
	'use strict';
	DevKit.ConnectionApi = function (e) {
		var f = '@OData.Community.Display.V1.FormattedValue';
		function webApiField(obj, field, entity, logicalName, schemaName, entityLogicalCollectionName, entityLogicalName, readOnly, upsertEntity, isMultiOptionSet) {
			var l = '@Microsoft.Dynamics.CRM.lookuplogicalname';
			var getFormattedValue = function () {
				if (entity[logicalName + f] === undefined || entity[logicalName + f] === null) {
					return '';
				}
				if (entityLogicalCollectionName !== undefined && entityLogicalCollectionName.length > 0) {
					if (entity[logicalName + l] === entityLogicalName) {
						return entity[logicalName + f];
					}
					return '';
				}
				if (isMultiOptionSet) {
					return entity[logicalName + f].toString().split(';').map(function (item) { return item.trim(); });
				}
				return entity[logicalName + f];
			};
			var getValue = function () {
				if (entity[logicalName] === undefined || entity[logicalName] === null) {
					return null;
				}
				if (entityLogicalCollectionName !== undefined && entityLogicalCollectionName.length > 0) {
					if (entity[logicalName + l] === undefined || entity[logicalName + l] === entityLogicalName) {
						return entity[logicalName];
					}
					return null;
				}
				if (isMultiOptionSet) {
					return entity[logicalName].toString().split(',').map(function (item) { return parseInt(item, 10); });
				}
				return entity[logicalName];
			};
			var setValue = function (value) {
				if (isMultiOptionSet) value = value.join(',');
				if (entityLogicalCollectionName !== undefined && entityLogicalCollectionName.length > 0) {
					value = value.replace('{', '').replace('}', '');
					upsertEntity[schemaName + '@odata.bind'] = '/' + entityLogicalCollectionName + '(' + value + ')';
				} else {
					upsertEntity[logicalName] = value;
				}
				entity[logicalName] = value;
			};
			Object.defineProperty(obj.FormattedValue, field, {
				get: getFormattedValue
			});
			if (readOnly) {
				Object.defineProperty(obj, field, {
					get: getValue
				});
			}
			else {
				Object.defineProperty(obj, field, {
					get: getValue,
					set: setValue
				});
			}
		}
		var _connection = {
			ConnectionId: { a: 'connectionid' },
			CreatedBy: { b: 'createdby', a: '_createdby_value', c: 'systemusers', d: 'systemuser', r: true },
			CreatedOn_UtcDateAndTime: { a: 'createdon', r: true },
			CreatedOnBehalfBy: { b: 'createdonbehalfby', a: '_createdonbehalfby_value', c: 'systemusers', d: 'systemuser', r: true },
			Description: { a: 'description' },
			EffectiveEnd_UtcDateOnly: { a: 'effectiveend' },
			EffectiveStart_UtcDateOnly: { a: 'effectivestart' },
			EntityImage: { a: 'entityimage' },
			EntityImage_Timestamp: { a: 'entityimage_timestamp', r: true },
			EntityImage_URL: { a: 'entityimage_url', r: true },
			EntityImageId: { a: 'entityimageid', r: true },
			ExchangeRate: { a: 'exchangerate', r: true },
			ImportSequenceNumber: { a: 'importsequencenumber' },
			IsMaster: { a: 'ismaster', r: true },
			ModifiedBy: { b: 'modifiedby', a: '_modifiedby_value', c: 'systemusers', d: 'systemuser', r: true },
			ModifiedOn_UtcDateAndTime: { a: 'modifiedon', r: true },
			ModifiedOnBehalfBy: { b: 'modifiedonbehalfby', a: '_modifiedonbehalfby_value', c: 'systemusers', d: 'systemuser', r: true },
			Name: { a: 'name', r: true },
			OverriddenCreatedOn_UtcDateOnly: { a: 'overriddencreatedon' },
			OwnerId_systemuser: { b: 'ownerid', a: '_ownerid_value', c: 'systemusers', d: 'systemuser' },
			OwnerId_team: { b: 'ownerid', a: '_ownerid_value', c: 'teams', d: 'team' },
			OwningBusinessUnit: { b: 'owningbusinessunit', a: '_owningbusinessunit_value', c: 'businessunits', d: 'businessunit', r: true },
			OwningTeam: { b: 'owningteam', a: '_owningteam_value', c: 'teams', d: 'team', r: true },
			OwningUser: { b: 'owninguser', a: '_owninguser_value', c: 'systemusers', d: 'systemuser', r: true },
			record1id_account: { b: 'record1id_account', a: '_record1id_value', c: 'accounts', d: 'account' },
			record1id_activitypointer: { b: 'record1id_activitypointer', a: '_record1id_value', c: 'activitypointers', d: 'activitypointer' },
			record1id_appointment: { b: 'record1id_appointment', a: '_record1id_value', c: 'appointments', d: 'appointment' },
			record1id_campaign: { b: 'record1id_campaign', a: '_record1id_value', c: 'campaigns', d: 'campaign' },
			record1id_campaignactivity: { b: 'record1id_campaignactivity', a: '_record1id_value', c: 'campaignactivities', d: 'campaignactivity' },
			profileruleid1: { b: 'profileruleid1', a: '_record1id_value', c: 'channelaccessprofilerules', d: 'channelaccessprofilerule' },
			record1id_competitor: { b: 'record1id_competitor', a: '_record1id_value', c: 'competitors', d: 'competitor' },
			record1id_constraintbasedgroup: { b: 'record1id_constraintbasedgroup', a: '_record1id_value', c: 'constraintbasedgroups', d: 'constraintbasedgroup' },
			record1id_contact: { b: 'record1id_contact', a: '_record1id_value', c: 'contacts', d: 'contact' },
			record1id_contract: { b: 'record1id_contract', a: '_record1id_value', c: 'contracts', d: 'contract' },
			record1id_email: { b: 'record1id_email', a: '_record1id_value', c: 'emails', d: 'email' },
			record1id_entitlement: { b: 'record1id_entitlement', a: '_record1id_value', c: 'entitlements', d: 'entitlement' },
			record1id_entitlementchannel: { b: 'record1id_entitlementchannel', a: '_record1id_value', c: 'entitlementchannels', d: 'entitlementchannel' },
			record1id_entitlementtemplatechannel: { b: 'record1id_entitlementtemplatechannel', a: '_record1id_value', c: 'entitlementtemplatechannels', d: 'entitlementtemplatechannel' },
			record1id_equipment: { b: 'record1id_equipment', a: '_record1id_value', c: 'equipments', d: 'equipment' },
			record1id_fax: { b: 'record1id_fax', a: '_record1id_value', c: 'faxes', d: 'fax' },
			record1id_goal: { b: 'record1id_goal', a: '_record1id_value', c: 'goals', d: 'goal' },
			record1id_incident: { b: 'record1id_incident', a: '_record1id_value', c: 'incidents', d: 'incident' },
			record1id_invoice: { b: 'record1id_invoice', a: '_record1id_value', c: 'invoices', d: 'invoice' },
			record1id_knowledgearticle: { b: 'record1id_knowledgearticle', a: '_record1id_value', c: 'knowledgearticles', d: 'knowledgearticle' },
			record1id_knowledgebaserecord: { b: 'record1id_knowledgebaserecord', a: '_record1id_value', c: 'knowledgebaserecords', d: 'knowledgebaserecord' },
			record1id_lead: { b: 'record1id_lead', a: '_record1id_value', c: 'leads', d: 'lead' },
			record1id_letter: { b: 'record1id_letter', a: '_record1id_value', c: 'letters', d: 'letter' },
			record1id_list: { b: 'record1id_list', a: '_record1id_value', c: 'lists', d: 'list' },
			record1id_msdyn_agreement: { b: 'record1id_msdyn_agreement', a: '_record1id_value', c: 'msdyn_agreements', d: 'msdyn_agreement' },
			record1id_msdyn_agreementbookingdate: { b: 'record1id_msdyn_agreementbookingdate', a: '_record1id_value', c: 'msdyn_agreementbookingdates', d: 'msdyn_agreementbookingdate' },
			record1id_msdyn_agreementbookingincident: { b: 'record1id_msdyn_agreementbookingincident', a: '_record1id_value', c: 'msdyn_agreementbookingincidents', d: 'msdyn_agreementbookingincident' },
			record1id_msdyn_agreementbookingproduct: { b: 'record1id_msdyn_agreementbookingproduct', a: '_record1id_value', c: 'msdyn_agreementbookingproducts', d: 'msdyn_agreementbookingproduct' },
			record1id_msdyn_agreementbookingservice: { b: 'record1id_msdyn_agreementbookingservice', a: '_record1id_value', c: 'msdyn_agreementbookingservices', d: 'msdyn_agreementbookingservice' },
			record1id_msdyn_agreementbookingservicetask: { b: 'record1id_msdyn_agreementbookingservicetask', a: '_record1id_value', c: 'msdyn_agreementbookingservicetasks', d: 'msdyn_agreementbookingservicetask' },
			record1id_msdyn_agreementbookingsetup: { b: 'record1id_msdyn_agreementbookingsetup', a: '_record1id_value', c: 'msdyn_agreementbookingsetups', d: 'msdyn_agreementbookingsetup' },
			record1id_msdyn_agreementinvoicedate: { b: 'record1id_msdyn_agreementinvoicedate', a: '_record1id_value', c: 'msdyn_agreementinvoicedates', d: 'msdyn_agreementinvoicedate' },
			record1id_msdyn_agreementinvoiceproduct: { b: 'record1id_msdyn_agreementinvoiceproduct', a: '_record1id_value', c: 'msdyn_agreementinvoiceproducts', d: 'msdyn_agreementinvoiceproduct' },
			record1id_msdyn_agreementinvoicesetup: { b: 'record1id_msdyn_agreementinvoicesetup', a: '_record1id_value', c: 'msdyn_agreementinvoicesetups', d: 'msdyn_agreementinvoicesetup' },
			record1id_msdyn_approval: { b: 'record1id_msdyn_approval', a: '_record1id_value', c: 'msdyn_approvals', d: 'msdyn_approval' },
			record1id_msdyn_assignmentmap: { b: 'record1id_msdyn_assignmentmap', a: '_record1id_value', c: 'msdyn_assignmentmaps', d: 'msdyn_assignmentmap' },
			record1id_msdyn_assignmentrule: { b: 'record1id_msdyn_assignmentrule', a: '_record1id_value', c: 'msdyn_assignmentrules', d: 'msdyn_assignmentrule' },
			record1id_msdyn_bookingalert: { b: 'record1id_msdyn_bookingalert', a: '_record1id_value', c: 'msdyn_bookingalerts', d: 'msdyn_bookingalert' },
			record1id_msdyn_bookingalertstatus: { b: 'record1id_msdyn_bookingalertstatus', a: '_record1id_value', c: 'msdyn_bookingalertstatuses', d: 'msdyn_bookingalertstatus' },
			record1id_msdyn_bookingrule: { b: 'record1id_msdyn_bookingrule', a: '_record1id_value', c: 'msdyn_bookingrules', d: 'msdyn_bookingrule' },
			record1id_msdyn_bookingtimestamp: { b: 'record1id_msdyn_bookingtimestamp', a: '_record1id_value', c: 'msdyn_bookingtimestamps', d: 'msdyn_bookingtimestamp' },
			record1id_msdyn_customerasset: { b: 'record1id_msdyn_customerasset', a: '_record1id_value', c: 'msdyn_customerassets', d: 'msdyn_customerasset' },
			record1id_msdyn_incidenttypecharacteristic: { b: 'record1id_msdyn_incidenttypecharacteristic', a: '_record1id_value', c: 'msdyn_incidenttypecharacteristics', d: 'msdyn_incidenttypecharacteristic' },
			record1id_msdyn_incidenttypeproduct: { b: 'record1id_msdyn_incidenttypeproduct', a: '_record1id_value', c: 'msdyn_incidenttypeproducts', d: 'msdyn_incidenttypeproduct' },
			record1id_msdyn_incidenttypeservice: { b: 'record1id_msdyn_incidenttypeservice', a: '_record1id_value', c: 'msdyn_incidenttypeservices', d: 'msdyn_incidenttypeservice' },
			record1id_msdyn_inventoryadjustment: { b: 'record1id_msdyn_inventoryadjustment', a: '_record1id_value', c: 'msdyn_inventoryadjustments', d: 'msdyn_inventoryadjustment' },
			record1id_msdyn_inventoryadjustmentproduct: { b: 'record1id_msdyn_inventoryadjustmentproduct', a: '_record1id_value', c: 'msdyn_inventoryadjustmentproducts', d: 'msdyn_inventoryadjustmentproduct' },
			record1id_msdyn_inventoryjournal: { b: 'record1id_msdyn_inventoryjournal', a: '_record1id_value', c: 'msdyn_inventoryjournals', d: 'msdyn_inventoryjournal' },
			record1id_msdyn_inventorytransfer: { b: 'record1id_msdyn_inventorytransfer', a: '_record1id_value', c: 'msdyn_inventorytransfers', d: 'msdyn_inventorytransfer' },
			record1id_msdyn_iotalert: { b: 'record1id_msdyn_iotalert', a: '_record1id_value', c: 'msdyn_iotalerts', d: 'msdyn_iotalert' },
			record1id_msdyn_iotdevice: { b: 'record1id_msdyn_iotdevice', a: '_record1id_value', c: 'msdyn_iotdevices', d: 'msdyn_iotdevice' },
			record1id_msdyn_iotdevicecategory: { b: 'record1id_msdyn_iotdevicecategory', a: '_record1id_value', c: 'msdyn_iotdevicecategories', d: 'msdyn_iotdevicecategory' },
			record1id_msdyn_iotdevicecommand: { b: 'record1id_msdyn_iotdevicecommand', a: '_record1id_value', c: 'msdyn_iotdevicecommands', d: 'msdyn_iotdevicecommand' },
			record1id_msdyn_iotdeviceregistrationhistory: { b: 'record1id_msdyn_iotdeviceregistrationhistory', a: '_record1id_value', c: 'msdyn_iotdeviceregistrationhistories', d: 'msdyn_iotdeviceregistrationhistory' },
			record1id_msdyn_liveconversation: { b: 'record1id_msdyn_liveconversation', a: '_record1id_value', c: 'msdyn_liveconversations', d: 'msdyn_liveconversation' },
			record1id_msdyn_ocliveworkitem: { b: 'record1id_msdyn_ocliveworkitem', a: '_record1id_value', c: 'msdyn_ocliveworkitems', d: 'msdyn_ocliveworkitem' },
			record1id_msdyn_ocoutboundmessage: { b: 'record1id_msdyn_ocoutboundmessage', a: '_record1id_value', c: 'msdyn_ocoutboundmessages', d: 'msdyn_ocoutboundmessage' },
			record1id_msdyn_ocsession: { b: 'record1id_msdyn_ocsession', a: '_record1id_value', c: 'msdyn_ocsessions', d: 'msdyn_ocsession' },
			record1id_msdyn_payment: { b: 'record1id_msdyn_payment', a: '_record1id_value', c: 'msdyn_payments', d: 'msdyn_payment' },
			record1id_msdyn_paymentdetail: { b: 'record1id_msdyn_paymentdetail', a: '_record1id_value', c: 'msdyn_paymentdetails', d: 'msdyn_paymentdetail' },
			record1id_msdyn_paymentmethod: { b: 'record1id_msdyn_paymentmethod', a: '_record1id_value', c: 'msdyn_paymentmethods', d: 'msdyn_paymentmethod' },
			record1id_msdyn_paymentterm: { b: 'record1id_msdyn_paymentterm', a: '_record1id_value', c: 'msdyn_paymentterms', d: 'msdyn_paymentterm' },
			record1id_msdyn_postalbum: { b: 'record1id_msdyn_postalbum', a: '_record1id_value', c: 'msdyn_postalbums', d: 'msdyn_postalbum' },
			record1id_msdyn_postalcode: { b: 'record1id_msdyn_postalcode', a: '_record1id_value', c: 'msdyn_postalcodes', d: 'msdyn_postalcode' },
			record1id_msdyn_processnotes: { b: 'record1id_msdyn_processnotes', a: '_record1id_value', c: 'msdyn_processnoteses', d: 'msdyn_processnotes' },
			record1id_msdyn_productinventory: { b: 'record1id_msdyn_productinventory', a: '_record1id_value', c: 'msdyn_productinventories', d: 'msdyn_productinventory' },
			record1id_msdyn_project: { b: 'record1id_msdyn_project', a: '_record1id_value', c: 'msdyn_projects', d: 'msdyn_project' },
			record1id_msdyn_projectteam: { b: 'record1id_msdyn_projectteam', a: '_record1id_value', c: 'msdyn_projectteams', d: 'msdyn_projectteam' },
			record1id_msdyn_purchaseorder: { b: 'record1id_msdyn_purchaseorder', a: '_record1id_value', c: 'msdyn_purchaseorders', d: 'msdyn_purchaseorder' },
			record1id_msdyn_purchaseorderbill: { b: 'record1id_msdyn_purchaseorderbill', a: '_record1id_value', c: 'msdyn_purchaseorderbills', d: 'msdyn_purchaseorderbill' },
			record1id_msdyn_purchaseorderproduct: { b: 'record1id_msdyn_purchaseorderproduct', a: '_record1id_value', c: 'msdyn_purchaseorderproducts', d: 'msdyn_purchaseorderproduct' },
			record1id_msdyn_purchaseorderreceipt: { b: 'record1id_msdyn_purchaseorderreceipt', a: '_record1id_value', c: 'msdyn_purchaseorderreceipts', d: 'msdyn_purchaseorderreceipt' },
			record1id_msdyn_purchaseorderreceiptproduct: { b: 'record1id_msdyn_purchaseorderreceiptproduct', a: '_record1id_value', c: 'msdyn_purchaseorderreceiptproducts', d: 'msdyn_purchaseorderreceiptproduct' },
			record1id_msdyn_purchaseordersubstatus: { b: 'record1id_msdyn_purchaseordersubstatus', a: '_record1id_value', c: 'msdyn_purchaseordersubstatuses', d: 'msdyn_purchaseordersubstatus' },
			record1id_msdyn_quotebookingincident: { b: 'record1id_msdyn_quotebookingincident', a: '_record1id_value', c: 'msdyn_quotebookingincidents', d: 'msdyn_quotebookingincident' },
			record1id_msdyn_quotebookingproduct: { b: 'record1id_msdyn_quotebookingproduct', a: '_record1id_value', c: 'msdyn_quotebookingproducts', d: 'msdyn_quotebookingproduct' },
			record1id_msdyn_quotebookingservice: { b: 'record1id_msdyn_quotebookingservice', a: '_record1id_value', c: 'msdyn_quotebookingservices', d: 'msdyn_quotebookingservice' },
			record1id_msdyn_quotebookingservicetask: { b: 'record1id_msdyn_quotebookingservicetask', a: '_record1id_value', c: 'msdyn_quotebookingservicetasks', d: 'msdyn_quotebookingservicetask' },
			record1id_msdyn_resourceterritory: { b: 'record1id_msdyn_resourceterritory', a: '_record1id_value', c: 'msdyn_resourceterritories', d: 'msdyn_resourceterritory' },
			record1id_msdyn_rma: { b: 'record1id_msdyn_rma', a: '_record1id_value', c: 'msdyn_rmas', d: 'msdyn_rma' },
			record1id_msdyn_rmaproduct: { b: 'record1id_msdyn_rmaproduct', a: '_record1id_value', c: 'msdyn_rmaproducts', d: 'msdyn_rmaproduct' },
			record1id_msdyn_rmareceipt: { b: 'record1id_msdyn_rmareceipt', a: '_record1id_value', c: 'msdyn_rmareceipts', d: 'msdyn_rmareceipt' },
			record1id_msdyn_rmareceiptproduct: { b: 'record1id_msdyn_rmareceiptproduct', a: '_record1id_value', c: 'msdyn_rmareceiptproducts', d: 'msdyn_rmareceiptproduct' },
			record1id_msdyn_rmasubstatus: { b: 'record1id_msdyn_rmasubstatus', a: '_record1id_value', c: 'msdyn_rmasubstatuses', d: 'msdyn_rmasubstatus' },
			record1id_msdyn_rtv: { b: 'record1id_msdyn_rtv', a: '_record1id_value', c: 'msdyn_rtvs', d: 'msdyn_rtv' },
			record1id_msdyn_rtvproduct: { b: 'record1id_msdyn_rtvproduct', a: '_record1id_value', c: 'msdyn_rtvproducts', d: 'msdyn_rtvproduct' },
			record1id_msdyn_rtvsubstatus: { b: 'record1id_msdyn_rtvsubstatus', a: '_record1id_value', c: 'msdyn_rtvsubstatuses', d: 'msdyn_rtvsubstatus' },
			record1id_msdyn_salessuggestion: { b: 'record1id_msdyn_salessuggestion', a: '_record1id_value', c: 'msdyn_salessuggestions', d: 'msdyn_salessuggestion' },
			record1id_msdyn_sequence: { b: 'record1id_msdyn_sequence', a: '_record1id_value', c: 'msdyn_sequences', d: 'msdyn_sequence' },
			record1id_msdyn_sequencetarget: { b: 'record1id_msdyn_sequencetarget', a: '_record1id_value', c: 'msdyn_sequencetargets', d: 'msdyn_sequencetarget' },
			record1id_msdyn_shipvia: { b: 'record1id_msdyn_shipvia', a: '_record1id_value', c: 'msdyn_shipvias', d: 'msdyn_shipvia' },
			record1id_msdyn_systemuserschedulersetting: { b: 'record1id_msdyn_systemuserschedulersetting', a: '_record1id_value', c: 'msdyn_systemuserschedulersettings', d: 'msdyn_systemuserschedulersetting' },
			record1id_msdyn_taxcode: { b: 'record1id_msdyn_taxcode', a: '_record1id_value', c: 'msdyn_taxcodes', d: 'msdyn_taxcode' },
			record1id_msdyn_timegroup: { b: 'record1id_msdyn_timegroup', a: '_record1id_value', c: 'msdyn_timegroups', d: 'msdyn_timegroup' },
			record1id_msdyn_timegroupdetail: { b: 'record1id_msdyn_timegroupdetail', a: '_record1id_value', c: 'msdyn_timegroupdetails', d: 'msdyn_timegroupdetail' },
			record1id_msdyn_timeoffrequest: { b: 'record1id_msdyn_timeoffrequest', a: '_record1id_value', c: 'msdyn_timeoffrequests', d: 'msdyn_timeoffrequest' },
			record1id_msdyn_warehouse: { b: 'record1id_msdyn_warehouse', a: '_record1id_value', c: 'msdyn_warehouses', d: 'msdyn_warehouse' },
			record1id_msdyn_workorder: { b: 'record1id_msdyn_workorder', a: '_record1id_value', c: 'msdyn_workorders', d: 'msdyn_workorder' },
			record1id_msdyn_workordercharacteristic: { b: 'record1id_msdyn_workordercharacteristic', a: '_record1id_value', c: 'msdyn_workordercharacteristics', d: 'msdyn_workordercharacteristic' },
			record1id_msdyn_workorderincident: { b: 'record1id_msdyn_workorderincident', a: '_record1id_value', c: 'msdyn_workorderincidents', d: 'msdyn_workorderincident' },
			record1id_msdyn_workorderproduct: { b: 'record1id_msdyn_workorderproduct', a: '_record1id_value', c: 'msdyn_workorderproducts', d: 'msdyn_workorderproduct' },
			record1id_msdyn_workorderresourcerestriction: { b: 'record1id_msdyn_workorderresourcerestriction', a: '_record1id_value', c: 'msdyn_workorderresourcerestrictions', d: 'msdyn_workorderresourcerestriction' },
			record1id_msdyn_workorderservice: { b: 'record1id_msdyn_workorderservice', a: '_record1id_value', c: 'msdyn_workorderservices', d: 'msdyn_workorderservice' },
			record1id_msdyn_workorderservicetask: { b: 'record1id_msdyn_workorderservicetask', a: '_record1id_value', c: 'msdyn_workorderservicetasks', d: 'msdyn_workorderservicetask' },
			record1id_msdyusd_toolbarbutton: { b: 'record1id_msdyusd_toolbarbutton', a: '_record1id_value', c: 'msdyusd_toolbarbuttons', d: 'msdyusd_toolbarbutton' },
			record1id_msfp_alert: { b: 'record1id_msfp_alert', a: '_record1id_value', c: 'msfp_alerts', d: 'msfp_alert' },
			record1id_msfp_surveyinvite: { b: 'record1id_msfp_surveyinvite', a: '_record1id_value', c: 'msfp_surveyinvites', d: 'msfp_surveyinvite' },
			record1id_msfp_surveyresponse: { b: 'record1id_msfp_surveyresponse', a: '_record1id_value', c: 'msfp_surveyresponses', d: 'msfp_surveyresponse' },
			record1id_opportunity: { b: 'record1id_opportunity', a: '_record1id_value', c: 'opportunities', d: 'opportunity' },
			record1id_phonecall: { b: 'record1id_phonecall', a: '_record1id_value', c: 'phonecalls', d: 'phonecall' },
			record1id_position: { b: 'record1id_position', a: '_record1id_value', c: 'positions', d: 'position' },
			record1id_pricelevel: { b: 'record1id_pricelevel', a: '_record1id_value', c: 'pricelevels', d: 'pricelevel' },
			record1id_processsession: { b: 'record1id_processsession', a: '_record1id_value', c: 'processsessions', d: 'processsession' },
			record1id_product: { b: 'record1id_product', a: '_record1id_value', c: 'products', d: 'product' },
			record1id_quote: { b: 'record1id_quote', a: '_record1id_value', c: 'quotes', d: 'quote' },
			record1id_recurringappointmentmaster: { b: 'record1id_recurringappointmentmaster', a: '_record1id_value', c: 'recurringappointmentmasters', d: 'recurringappointmentmaster' },
			record1id_resourcegroup: { b: 'record1id_resourcegroup', a: '_record1id_value', c: 'resourcegroups', d: 'resourcegroup' },
			record1id_salesorder: { b: 'record1id_salesorder', a: '_record1id_value', c: 'salesorders', d: 'salesorder' },
			record1id_serviceappointment: { b: 'record1id_serviceappointment', a: '_record1id_value', c: 'serviceappointments', d: 'serviceappointment' },
			record1id_socialactivity: { b: 'record1id_socialactivity', a: '_record1id_value', c: 'socialactivities', d: 'socialactivity' },
			record1id_socialprofile: { b: 'record1id_socialprofile', a: '_record1id_value', c: 'socialprofiles', d: 'socialprofile' },
			record1id_systemuser: { b: 'record1id_systemuser', a: '_record1id_value', c: 'systemusers', d: 'systemuser' },
			record1id_task: { b: 'record1id_task', a: '_record1id_value', c: 'tasks', d: 'task' },
			record1id_team: { b: 'record1id_team', a: '_record1id_value', c: 'teams', d: 'team' },
			record1id_territory: { b: 'record1id_territory', a: '_record1id_value', c: 'territories', d: 'territory' },
			record1id_uii_option: { b: 'record1id_uii_option', a: '_record1id_value', c: 'uii_options', d: 'uii_option' },
			Record1ObjectTypeCode: { a: 'record1objecttypecode', r: true },
			Record1RoleId: { b: 'record1roleid', a: '_record1roleid_value', c: 'connectionroles', d: 'connectionrole' },
			record2id_account: { b: 'record2id_account', a: '_record2id_value', c: 'accounts', d: 'account' },
			record2id_activitypointer: { b: 'record2id_activitypointer', a: '_record2id_value', c: 'activitypointers', d: 'activitypointer' },
			record2id_appointment: { b: 'record2id_appointment', a: '_record2id_value', c: 'appointments', d: 'appointment' },
			record2id_campaign: { b: 'record2id_campaign', a: '_record2id_value', c: 'campaigns', d: 'campaign' },
			record2id_campaignactivity: { b: 'record2id_campaignactivity', a: '_record2id_value', c: 'campaignactivities', d: 'campaignactivity' },
			channelaccessprofileruleid: { b: 'channelaccessprofileruleid', a: '_record2id_value', c: 'channelaccessprofilerules', d: 'channelaccessprofilerule' },
			record2id_competitor: { b: 'record2id_competitor', a: '_record2id_value', c: 'competitors', d: 'competitor' },
			record2id_constraintbasedgroup: { b: 'record2id_constraintbasedgroup', a: '_record2id_value', c: 'constraintbasedgroups', d: 'constraintbasedgroup' },
			record2id_contact: { b: 'record2id_contact', a: '_record2id_value', c: 'contacts', d: 'contact' },
			record2id_contract: { b: 'record2id_contract', a: '_record2id_value', c: 'contracts', d: 'contract' },
			record2id_email: { b: 'record2id_email', a: '_record2id_value', c: 'emails', d: 'email' },
			record2id_entitlement: { b: 'record2id_entitlement', a: '_record2id_value', c: 'entitlements', d: 'entitlement' },
			record2id_entitlementchannel: { b: 'record2id_entitlementchannel', a: '_record2id_value', c: 'entitlementchannels', d: 'entitlementchannel' },
			record2id_entitlementtemplatechannel: { b: 'record2id_entitlementtemplatechannel', a: '_record2id_value', c: 'entitlementtemplatechannels', d: 'entitlementtemplatechannel' },
			record2id_equipment: { b: 'record2id_equipment', a: '_record2id_value', c: 'equipments', d: 'equipment' },
			record2id_fax: { b: 'record2id_fax', a: '_record2id_value', c: 'faxes', d: 'fax' },
			record2id_goal: { b: 'record2id_goal', a: '_record2id_value', c: 'goals', d: 'goal' },
			record2id_incident: { b: 'record2id_incident', a: '_record2id_value', c: 'incidents', d: 'incident' },
			record2id_invoice: { b: 'record2id_invoice', a: '_record2id_value', c: 'invoices', d: 'invoice' },
			record2id_knowledgearticle: { b: 'record2id_knowledgearticle', a: '_record2id_value', c: 'knowledgearticles', d: 'knowledgearticle' },
			record2id_knowledgebaserecord: { b: 'record2id_knowledgebaserecord', a: '_record2id_value', c: 'knowledgebaserecords', d: 'knowledgebaserecord' },
			record2id_lead: { b: 'record2id_lead', a: '_record2id_value', c: 'leads', d: 'lead' },
			record2id_letter: { b: 'record2id_letter', a: '_record2id_value', c: 'letters', d: 'letter' },
			record2id_list: { b: 'record2id_list', a: '_record2id_value', c: 'lists', d: 'list' },
			record2id_msdyn_agreement: { b: 'record2id_msdyn_agreement', a: '_record2id_value', c: 'msdyn_agreements', d: 'msdyn_agreement' },
			record2id_msdyn_agreementbookingdate: { b: 'record2id_msdyn_agreementbookingdate', a: '_record2id_value', c: 'msdyn_agreementbookingdates', d: 'msdyn_agreementbookingdate' },
			record2id_msdyn_agreementbookingincident: { b: 'record2id_msdyn_agreementbookingincident', a: '_record2id_value', c: 'msdyn_agreementbookingincidents', d: 'msdyn_agreementbookingincident' },
			record2id_msdyn_agreementbookingproduct: { b: 'record2id_msdyn_agreementbookingproduct', a: '_record2id_value', c: 'msdyn_agreementbookingproducts', d: 'msdyn_agreementbookingproduct' },
			record2id_msdyn_agreementbookingservice: { b: 'record2id_msdyn_agreementbookingservice', a: '_record2id_value', c: 'msdyn_agreementbookingservices', d: 'msdyn_agreementbookingservice' },
			record2id_msdyn_agreementbookingservicetask: { b: 'record2id_msdyn_agreementbookingservicetask', a: '_record2id_value', c: 'msdyn_agreementbookingservicetasks', d: 'msdyn_agreementbookingservicetask' },
			record2id_msdyn_agreementbookingsetup: { b: 'record2id_msdyn_agreementbookingsetup', a: '_record2id_value', c: 'msdyn_agreementbookingsetups', d: 'msdyn_agreementbookingsetup' },
			record2id_msdyn_agreementinvoicedate: { b: 'record2id_msdyn_agreementinvoicedate', a: '_record2id_value', c: 'msdyn_agreementinvoicedates', d: 'msdyn_agreementinvoicedate' },
			record2id_msdyn_agreementinvoiceproduct: { b: 'record2id_msdyn_agreementinvoiceproduct', a: '_record2id_value', c: 'msdyn_agreementinvoiceproducts', d: 'msdyn_agreementinvoiceproduct' },
			record2id_msdyn_agreementinvoicesetup: { b: 'record2id_msdyn_agreementinvoicesetup', a: '_record2id_value', c: 'msdyn_agreementinvoicesetups', d: 'msdyn_agreementinvoicesetup' },
			record2id_msdyn_approval: { b: 'record2id_msdyn_approval', a: '_record2id_value', c: 'msdyn_approvals', d: 'msdyn_approval' },
			record2id_msdyn_assignmentmap: { b: 'record2id_msdyn_assignmentmap', a: '_record2id_value', c: 'msdyn_assignmentmaps', d: 'msdyn_assignmentmap' },
			record2id_msdyn_assignmentrule: { b: 'record2id_msdyn_assignmentrule', a: '_record2id_value', c: 'msdyn_assignmentrules', d: 'msdyn_assignmentrule' },
			record2id_msdyn_bookingalert: { b: 'record2id_msdyn_bookingalert', a: '_record2id_value', c: 'msdyn_bookingalerts', d: 'msdyn_bookingalert' },
			record2id_msdyn_bookingalertstatus: { b: 'record2id_msdyn_bookingalertstatus', a: '_record2id_value', c: 'msdyn_bookingalertstatuses', d: 'msdyn_bookingalertstatus' },
			record2id_msdyn_bookingrule: { b: 'record2id_msdyn_bookingrule', a: '_record2id_value', c: 'msdyn_bookingrules', d: 'msdyn_bookingrule' },
			record2id_msdyn_bookingtimestamp: { b: 'record2id_msdyn_bookingtimestamp', a: '_record2id_value', c: 'msdyn_bookingtimestamps', d: 'msdyn_bookingtimestamp' },
			record2id_msdyn_customerasset: { b: 'record2id_msdyn_customerasset', a: '_record2id_value', c: 'msdyn_customerassets', d: 'msdyn_customerasset' },
			record2id_msdyn_incidenttypecharacteristic: { b: 'record2id_msdyn_incidenttypecharacteristic', a: '_record2id_value', c: 'msdyn_incidenttypecharacteristics', d: 'msdyn_incidenttypecharacteristic' },
			record2id_msdyn_incidenttypeproduct: { b: 'record2id_msdyn_incidenttypeproduct', a: '_record2id_value', c: 'msdyn_incidenttypeproducts', d: 'msdyn_incidenttypeproduct' },
			record2id_msdyn_incidenttypeservice: { b: 'record2id_msdyn_incidenttypeservice', a: '_record2id_value', c: 'msdyn_incidenttypeservices', d: 'msdyn_incidenttypeservice' },
			record2id_msdyn_inventoryadjustment: { b: 'record2id_msdyn_inventoryadjustment', a: '_record2id_value', c: 'msdyn_inventoryadjustments', d: 'msdyn_inventoryadjustment' },
			record2id_msdyn_inventoryadjustmentproduct: { b: 'record2id_msdyn_inventoryadjustmentproduct', a: '_record2id_value', c: 'msdyn_inventoryadjustmentproducts', d: 'msdyn_inventoryadjustmentproduct' },
			record2id_msdyn_inventoryjournal: { b: 'record2id_msdyn_inventoryjournal', a: '_record2id_value', c: 'msdyn_inventoryjournals', d: 'msdyn_inventoryjournal' },
			record2id_msdyn_inventorytransfer: { b: 'record2id_msdyn_inventorytransfer', a: '_record2id_value', c: 'msdyn_inventorytransfers', d: 'msdyn_inventorytransfer' },
			record2id_msdyn_iotalert: { b: 'record2id_msdyn_iotalert', a: '_record2id_value', c: 'msdyn_iotalerts', d: 'msdyn_iotalert' },
			record2id_msdyn_iotdevice: { b: 'record2id_msdyn_iotdevice', a: '_record2id_value', c: 'msdyn_iotdevices', d: 'msdyn_iotdevice' },
			record2id_msdyn_iotdevicecategory: { b: 'record2id_msdyn_iotdevicecategory', a: '_record2id_value', c: 'msdyn_iotdevicecategories', d: 'msdyn_iotdevicecategory' },
			record2id_msdyn_iotdevicecommand: { b: 'record2id_msdyn_iotdevicecommand', a: '_record2id_value', c: 'msdyn_iotdevicecommands', d: 'msdyn_iotdevicecommand' },
			record2id_msdyn_iotdeviceregistrationhistory: { b: 'record2id_msdyn_iotdeviceregistrationhistory', a: '_record2id_value', c: 'msdyn_iotdeviceregistrationhistories', d: 'msdyn_iotdeviceregistrationhistory' },
			record2id_msdyn_liveconversation: { b: 'record2id_msdyn_liveconversation', a: '_record2id_value', c: 'msdyn_liveconversations', d: 'msdyn_liveconversation' },
			record2id_msdyn_ocliveworkitem: { b: 'record2id_msdyn_ocliveworkitem', a: '_record2id_value', c: 'msdyn_ocliveworkitems', d: 'msdyn_ocliveworkitem' },
			record2id_msdyn_ocoutboundmessage: { b: 'record2id_msdyn_ocoutboundmessage', a: '_record2id_value', c: 'msdyn_ocoutboundmessages', d: 'msdyn_ocoutboundmessage' },
			record2id_msdyn_ocsession: { b: 'record2id_msdyn_ocsession', a: '_record2id_value', c: 'msdyn_ocsessions', d: 'msdyn_ocsession' },
			record2id_msdyn_payment: { b: 'record2id_msdyn_payment', a: '_record2id_value', c: 'msdyn_payments', d: 'msdyn_payment' },
			record2id_msdyn_paymentdetail: { b: 'record2id_msdyn_paymentdetail', a: '_record2id_value', c: 'msdyn_paymentdetails', d: 'msdyn_paymentdetail' },
			record2id_msdyn_paymentmethod: { b: 'record2id_msdyn_paymentmethod', a: '_record2id_value', c: 'msdyn_paymentmethods', d: 'msdyn_paymentmethod' },
			record2id_msdyn_paymentterm: { b: 'record2id_msdyn_paymentterm', a: '_record2id_value', c: 'msdyn_paymentterms', d: 'msdyn_paymentterm' },
			record2id_msdyn_postalbum: { b: 'record2id_msdyn_postalbum', a: '_record2id_value', c: 'msdyn_postalbums', d: 'msdyn_postalbum' },
			record2id_msdyn_postalcode: { b: 'record2id_msdyn_postalcode', a: '_record2id_value', c: 'msdyn_postalcodes', d: 'msdyn_postalcode' },
			record2id_msdyn_processnotes: { b: 'record2id_msdyn_processnotes', a: '_record2id_value', c: 'msdyn_processnoteses', d: 'msdyn_processnotes' },
			record2id_msdyn_productinventory: { b: 'record2id_msdyn_productinventory', a: '_record2id_value', c: 'msdyn_productinventories', d: 'msdyn_productinventory' },
			record2id_msdyn_project: { b: 'record2id_msdyn_project', a: '_record2id_value', c: 'msdyn_projects', d: 'msdyn_project' },
			record2id_msdyn_projectteam: { b: 'record2id_msdyn_projectteam', a: '_record2id_value', c: 'msdyn_projectteams', d: 'msdyn_projectteam' },
			record2id_msdyn_purchaseorder: { b: 'record2id_msdyn_purchaseorder', a: '_record2id_value', c: 'msdyn_purchaseorders', d: 'msdyn_purchaseorder' },
			record2id_msdyn_purchaseorderbill: { b: 'record2id_msdyn_purchaseorderbill', a: '_record2id_value', c: 'msdyn_purchaseorderbills', d: 'msdyn_purchaseorderbill' },
			record2id_msdyn_purchaseorderproduct: { b: 'record2id_msdyn_purchaseorderproduct', a: '_record2id_value', c: 'msdyn_purchaseorderproducts', d: 'msdyn_purchaseorderproduct' },
			record2id_msdyn_purchaseorderreceipt: { b: 'record2id_msdyn_purchaseorderreceipt', a: '_record2id_value', c: 'msdyn_purchaseorderreceipts', d: 'msdyn_purchaseorderreceipt' },
			record2id_msdyn_purchaseorderreceiptproduct: { b: 'record2id_msdyn_purchaseorderreceiptproduct', a: '_record2id_value', c: 'msdyn_purchaseorderreceiptproducts', d: 'msdyn_purchaseorderreceiptproduct' },
			record2id_msdyn_purchaseordersubstatus: { b: 'record2id_msdyn_purchaseordersubstatus', a: '_record2id_value', c: 'msdyn_purchaseordersubstatuses', d: 'msdyn_purchaseordersubstatus' },
			record2id_msdyn_quotebookingincident: { b: 'record2id_msdyn_quotebookingincident', a: '_record2id_value', c: 'msdyn_quotebookingincidents', d: 'msdyn_quotebookingincident' },
			record2id_msdyn_quotebookingproduct: { b: 'record2id_msdyn_quotebookingproduct', a: '_record2id_value', c: 'msdyn_quotebookingproducts', d: 'msdyn_quotebookingproduct' },
			record2id_msdyn_quotebookingservice: { b: 'record2id_msdyn_quotebookingservice', a: '_record2id_value', c: 'msdyn_quotebookingservices', d: 'msdyn_quotebookingservice' },
			record2id_msdyn_quotebookingservicetask: { b: 'record2id_msdyn_quotebookingservicetask', a: '_record2id_value', c: 'msdyn_quotebookingservicetasks', d: 'msdyn_quotebookingservicetask' },
			record2id_msdyn_resourceterritory: { b: 'record2id_msdyn_resourceterritory', a: '_record2id_value', c: 'msdyn_resourceterritories', d: 'msdyn_resourceterritory' },
			record2id_msdyn_rma: { b: 'record2id_msdyn_rma', a: '_record2id_value', c: 'msdyn_rmas', d: 'msdyn_rma' },
			record2id_msdyn_rmaproduct: { b: 'record2id_msdyn_rmaproduct', a: '_record2id_value', c: 'msdyn_rmaproducts', d: 'msdyn_rmaproduct' },
			record2id_msdyn_rmareceipt: { b: 'record2id_msdyn_rmareceipt', a: '_record2id_value', c: 'msdyn_rmareceipts', d: 'msdyn_rmareceipt' },
			record2id_msdyn_rmareceiptproduct: { b: 'record2id_msdyn_rmareceiptproduct', a: '_record2id_value', c: 'msdyn_rmareceiptproducts', d: 'msdyn_rmareceiptproduct' },
			record2id_msdyn_rmasubstatus: { b: 'record2id_msdyn_rmasubstatus', a: '_record2id_value', c: 'msdyn_rmasubstatuses', d: 'msdyn_rmasubstatus' },
			record2id_msdyn_rtv: { b: 'record2id_msdyn_rtv', a: '_record2id_value', c: 'msdyn_rtvs', d: 'msdyn_rtv' },
			record2id_msdyn_rtvproduct: { b: 'record2id_msdyn_rtvproduct', a: '_record2id_value', c: 'msdyn_rtvproducts', d: 'msdyn_rtvproduct' },
			record2id_msdyn_rtvsubstatus: { b: 'record2id_msdyn_rtvsubstatus', a: '_record2id_value', c: 'msdyn_rtvsubstatuses', d: 'msdyn_rtvsubstatus' },
			record2id_msdyn_salessuggestion: { b: 'record2id_msdyn_salessuggestion', a: '_record2id_value', c: 'msdyn_salessuggestions', d: 'msdyn_salessuggestion' },
			record2id_msdyn_sequence: { b: 'record2id_msdyn_sequence', a: '_record2id_value', c: 'msdyn_sequences', d: 'msdyn_sequence' },
			record2id_msdyn_sequencetarget: { b: 'record2id_msdyn_sequencetarget', a: '_record2id_value', c: 'msdyn_sequencetargets', d: 'msdyn_sequencetarget' },
			record2id_msdyn_shipvia: { b: 'record2id_msdyn_shipvia', a: '_record2id_value', c: 'msdyn_shipvias', d: 'msdyn_shipvia' },
			record2id_msdyn_systemuserschedulersetting: { b: 'record2id_msdyn_systemuserschedulersetting', a: '_record2id_value', c: 'msdyn_systemuserschedulersettings', d: 'msdyn_systemuserschedulersetting' },
			record2id_msdyn_taxcode: { b: 'record2id_msdyn_taxcode', a: '_record2id_value', c: 'msdyn_taxcodes', d: 'msdyn_taxcode' },
			record2id_msdyn_timegroup: { b: 'record2id_msdyn_timegroup', a: '_record2id_value', c: 'msdyn_timegroups', d: 'msdyn_timegroup' },
			record2id_msdyn_timegroupdetail: { b: 'record2id_msdyn_timegroupdetail', a: '_record2id_value', c: 'msdyn_timegroupdetails', d: 'msdyn_timegroupdetail' },
			record2id_msdyn_timeoffrequest: { b: 'record2id_msdyn_timeoffrequest', a: '_record2id_value', c: 'msdyn_timeoffrequests', d: 'msdyn_timeoffrequest' },
			record2id_msdyn_warehouse: { b: 'record2id_msdyn_warehouse', a: '_record2id_value', c: 'msdyn_warehouses', d: 'msdyn_warehouse' },
			record2id_msdyn_workorder: { b: 'record2id_msdyn_workorder', a: '_record2id_value', c: 'msdyn_workorders', d: 'msdyn_workorder' },
			record2id_msdyn_workordercharacteristic: { b: 'record2id_msdyn_workordercharacteristic', a: '_record2id_value', c: 'msdyn_workordercharacteristics', d: 'msdyn_workordercharacteristic' },
			record2id_msdyn_workorderincident: { b: 'record2id_msdyn_workorderincident', a: '_record2id_value', c: 'msdyn_workorderincidents', d: 'msdyn_workorderincident' },
			record2id_msdyn_workorderproduct: { b: 'record2id_msdyn_workorderproduct', a: '_record2id_value', c: 'msdyn_workorderproducts', d: 'msdyn_workorderproduct' },
			record2id_msdyn_workorderresourcerestriction: { b: 'record2id_msdyn_workorderresourcerestriction', a: '_record2id_value', c: 'msdyn_workorderresourcerestrictions', d: 'msdyn_workorderresourcerestriction' },
			record2id_msdyn_workorderservice: { b: 'record2id_msdyn_workorderservice', a: '_record2id_value', c: 'msdyn_workorderservices', d: 'msdyn_workorderservice' },
			record2id_msdyn_workorderservicetask: { b: 'record2id_msdyn_workorderservicetask', a: '_record2id_value', c: 'msdyn_workorderservicetasks', d: 'msdyn_workorderservicetask' },
			record2id_msdyusd_toolbarbutton: { b: 'record2id_msdyusd_toolbarbutton', a: '_record2id_value', c: 'msdyusd_toolbarbuttons', d: 'msdyusd_toolbarbutton' },
			record2id_msfp_alert: { b: 'record2id_msfp_alert', a: '_record2id_value', c: 'msfp_alerts', d: 'msfp_alert' },
			record2id_msfp_surveyinvite: { b: 'record2id_msfp_surveyinvite', a: '_record2id_value', c: 'msfp_surveyinvites', d: 'msfp_surveyinvite' },
			record2id_msfp_surveyresponse: { b: 'record2id_msfp_surveyresponse', a: '_record2id_value', c: 'msfp_surveyresponses', d: 'msfp_surveyresponse' },
			record2id_opportunity: { b: 'record2id_opportunity', a: '_record2id_value', c: 'opportunities', d: 'opportunity' },
			record2id_phonecall: { b: 'record2id_phonecall', a: '_record2id_value', c: 'phonecalls', d: 'phonecall' },
			record2id_position: { b: 'record2id_position', a: '_record2id_value', c: 'positions', d: 'position' },
			record2id_pricelevel: { b: 'record2id_pricelevel', a: '_record2id_value', c: 'pricelevels', d: 'pricelevel' },
			record2id_processsession: { b: 'record2id_processsession', a: '_record2id_value', c: 'processsessions', d: 'processsession' },
			record2id_product: { b: 'record2id_product', a: '_record2id_value', c: 'products', d: 'product' },
			record2id_quote: { b: 'record2id_quote', a: '_record2id_value', c: 'quotes', d: 'quote' },
			record2id_recurringappointmentmaster: { b: 'record2id_recurringappointmentmaster', a: '_record2id_value', c: 'recurringappointmentmasters', d: 'recurringappointmentmaster' },
			record2id_resourcegroup: { b: 'record2id_resourcegroup', a: '_record2id_value', c: 'resourcegroups', d: 'resourcegroup' },
			record2id_salesorder: { b: 'record2id_salesorder', a: '_record2id_value', c: 'salesorders', d: 'salesorder' },
			record2id_serviceappointment: { b: 'record2id_serviceappointment', a: '_record2id_value', c: 'serviceappointments', d: 'serviceappointment' },
			record2id_socialactivity: { b: 'record2id_socialactivity', a: '_record2id_value', c: 'socialactivities', d: 'socialactivity' },
			record2id_socialprofile: { b: 'record2id_socialprofile', a: '_record2id_value', c: 'socialprofiles', d: 'socialprofile' },
			record2id_systemuser: { b: 'record2id_systemuser', a: '_record2id_value', c: 'systemusers', d: 'systemuser' },
			record2id_task: { b: 'record2id_task', a: '_record2id_value', c: 'tasks', d: 'task' },
			record2id_team: { b: 'record2id_team', a: '_record2id_value', c: 'teams', d: 'team' },
			record2id_territory: { b: 'record2id_territory', a: '_record2id_value', c: 'territories', d: 'territory' },
			record2id_uii_option: { b: 'record2id_uii_option', a: '_record2id_value', c: 'uii_options', d: 'uii_option' },
			Record2ObjectTypeCode: { a: 'record2objecttypecode', r: true },
			Record2RoleId: { b: 'record2roleid', a: '_record2roleid_value', c: 'connectionroles', d: 'connectionrole' },
			RelatedConnectionId: { b: 'relatedconnectionid', a: '_relatedconnectionid_value', c: 'connections', d: 'connection', r: true },
			StateCode: { a: 'statecode' },
			StatusCode: { a: 'statuscode' },
			TransactionCurrencyId: { b: 'transactioncurrencyid', a: '_transactioncurrencyid_value', c: 'transactioncurrencies', d: 'transactioncurrency' },
			VersionNumber: { a: 'versionnumber', r: true }
		};
		if (e === undefined) e = {};
		var u = {};
		var connection = {};
		connection.ODataEntity = e;
		connection.FormattedValue = {};
		for (var field in _connection) {
			var a = _connection[field].a;
			var b = _connection[field].b;
			var c = _connection[field].c;
			var d = _connection[field].d;
			var g = _connection[field].g;
			var r = _connection[field].r;
			webApiField(connection, field, e, a, b, c, d, r, u, g);
		}
		connection.Entity = u;
		connection.EntityName = 'connection';
		connection.EntityCollectionName = 'connections';
		connection['@odata.etag'] = e['@odata.etag'];
		connection.getAliasedValue = function (alias, isMultiOptionSet = false) {
			if (e[alias] === undefined || e[alias] === null) {
				return null;
			}
			if (isMultiOptionSet) {
				return e[alias].toString().split(',').map(function (item) { return parseInt(item, 10); });
			}
			return e[alias];
		}
		connection.getAliasedFormattedValue = function (alias, isMultiOptionSet = false) {
			if (e[alias + f] === undefined || e[alias + f] === null) {
				return EMPTY_STRING;
			}
			if (isMultiOptionSet) {
				return e[alias + f].toString().split(';').map(function (item) { return item.trim(); });
			}
			return e[alias + f];
		}
		return connection;
	};
})(DevKit || (DevKit = {}));
/** @namespace OptionSet */
var OptionSet;
(function (OptionSet) {
	OptionSet.Connection = {
		Record1ObjectTypeCode : {
			Account: 1,
			Activity: 4200,
			Agreement: 10524,
			Agreement_Booking_Date: 10525,
			Agreement_Booking_Incident: 10526,
			Agreement_Booking_Product: 10527,
			Agreement_Booking_Service: 10528,
			Agreement_Booking_Service_Task: 10529,
			Agreement_Booking_Setup: 10530,
			Agreement_Invoice_Date: 10531,
			Agreement_Invoice_Product: 10532,
			Agreement_Invoice_Setup: 10533,
			Appointment: 4201,
			Assignment_Map: 10283,
			Assignment_Rule: 10280,
			Booking_Alert: 10404,
			Booking_Alert_Status: 10405,
			Booking_Rule: 10407,
			Booking_Timestamp: 10536,
			Campaign: 4400,
			Campaign_Activity: 4402,
			Case: 112,
			Channel_Access_Profile_Rule: 9400,
			Competitor: 123,
			Contact: 2,
			Contract: 1010,
			Conversation: 10707,
			Customer_Asset: 10141,
			Customer_Voice_alert: 10313,
			Customer_Voice_survey_invite: 10323,
			Customer_Voice_survey_response: 10325,
			Email: 4202,
			Entitlement: 9700,
			Entitlement_Channel: 9701,
			Entitlement_Template_Channel: 9703,
			FacilityEquipment: 4000,
			Fax: 4204,
			Fulfillment_Preference: 10427,
			Goal: 9600,
			Incident_Type_Characteristic: 10547,
			Incident_Type_Product: 10548,
			Incident_Type_Service: 10549,
			Inventory_Adjustment: 10553,
			Inventory_Adjustment_Product: 10554,
			Inventory_Journal: 10555,
			Inventory_Transfer: 10556,
			Invoice: 1090,
			IoT_Alert: 10152,
			IoT_Device: 10153,
			IoT_Device_Category: 10154,
			IoT_Device_Command: 10155,
			IoT_Device_Registration_History: 10159,
			Knowledge_Article: 9953,
			Knowledge_Base_Record: 9930,
			Lead: 4,
			Letter: 4207,
			Marketing_List: 4300,
			Ongoing_conversation_Deprecated: 10697,
			Opportunity: 3,
			Option: 10823,
			Order: 1088,
			Outbound_message: 10817,
			Payment: 10561,
			Payment_Detail: 10562,
			Payment_Method: 10563,
			Payment_Term: 10564,
			Phone_Call: 4210,
			Position: 50,
			Postal_Code: 10565,
			Price_List: 1022,
			Process_Notes: 10472,
			Process_Session: 4710,
			Product: 1024,
			Product_Inventory: 10566,
			Profile_Album: 10308,
			Project: 10473,
			Project_Service_Approval: 10434,
			Project_Team_Member: 10481,
			Purchase_Order: 10567,
			Purchase_Order_Bill: 10568,
			Purchase_Order_Product: 10569,
			Purchase_Order_Receipt: 10570,
			Purchase_Order_Receipt_Product: 10571,
			Purchase_Order_SubStatus: 10572,
			Quote: 1084,
			Quote_Booking_Incident: 10573,
			Quote_Booking_Product: 10574,
			Quote_Booking_Service: 10575,
			Quote_Booking_Service_Task: 10576,
			Recurring_Appointment: 4251,
			Resource_Group: 4007,
			Resource_Restriction_Deprecated: 10601,
			Resource_Territory: 10423,
			RMA: 10581,
			RMA_Product: 10582,
			RMA_Receipt: 10583,
			RMA_Receipt_Product: 10584,
			RMA_SubStatus: 10585,
			RTV: 10586,
			RTV_Product: 10587,
			RTV_Substatus: 10588,
			Scheduling_Group: 4005,
			Sequence: 10273,
			Sequence_Target: 10275,
			Service_Activity: 4214,
			Session: 10721,
			Ship_Via: 10590,
			Social_Activity: 4216,
			Social_Profile: 99,
			Suggestion: 10289,
			System_User_Scheduler_Setting: 10426,
			Task: 4212,
			Tax_Code: 10591,
			Team: 9,
			Territory: 2013,
			Time_Group_Detail: 10428,
			Time_Off_Request: 10593,
			Toolbar_Button: 10846,
			User: 8,
			Warehouse: 10595,
			Work_Order: 10596,
			Work_Order_Characteristic_Deprecated: 10597,
			Work_Order_Incident: 10599,
			Work_Order_Product: 10600,
			Work_Order_Service: 10602,
			Work_Order_Service_Task: 10603
		},
		Record2ObjectTypeCode : {
			Account: 1,
			Activity: 4200,
			Agreement: 10524,
			Agreement_Booking_Date: 10525,
			Agreement_Booking_Incident: 10526,
			Agreement_Booking_Product: 10527,
			Agreement_Booking_Service: 10528,
			Agreement_Booking_Service_Task: 10529,
			Agreement_Booking_Setup: 10530,
			Agreement_Invoice_Date: 10531,
			Agreement_Invoice_Product: 10532,
			Agreement_Invoice_Setup: 10533,
			Appointment: 4201,
			Assignment_Map: 10283,
			Assignment_Rule: 10280,
			Booking_Alert: 10404,
			Booking_Alert_Status: 10405,
			Booking_Rule: 10407,
			Booking_Timestamp: 10536,
			Campaign: 4400,
			Campaign_Activity: 4402,
			Case: 112,
			Channel_Access_Profile_Rule: 9400,
			Competitor: 123,
			Contact: 2,
			Contract: 1010,
			Conversation: 10707,
			Customer_Asset: 10141,
			Customer_Voice_alert: 10313,
			Customer_Voice_survey_invite: 10323,
			Customer_Voice_survey_response: 10325,
			Email: 4202,
			Entitlement: 9700,
			Entitlement_Channel: 9701,
			Entitlement_Template_Channel: 9703,
			FacilityEquipment: 4000,
			Fax: 4204,
			Fulfillment_Preference: 10427,
			Goal: 9600,
			Incident_Type_Characteristic: 10547,
			Incident_Type_Product: 10548,
			Incident_Type_Service: 10549,
			Inventory_Adjustment: 10553,
			Inventory_Adjustment_Product: 10554,
			Inventory_Journal: 10555,
			Inventory_Transfer: 10556,
			Invoice: 1090,
			IoT_Alert: 10152,
			IoT_Device: 10153,
			IoT_Device_Category: 10154,
			IoT_Device_Command: 10155,
			IoT_Device_Registration_History: 10159,
			Knowledge_Article: 9953,
			Knowledge_Base_Record: 9930,
			Lead: 4,
			Letter: 4207,
			Marketing_List: 4300,
			Ongoing_conversation_Deprecated: 10697,
			Opportunity: 3,
			Option: 10823,
			Order: 1088,
			Outbound_message: 10817,
			Payment: 10561,
			Payment_Detail: 10562,
			Payment_Method: 10563,
			Payment_Term: 10564,
			Phone_Call: 4210,
			Position: 50,
			Postal_Code: 10565,
			Price_List: 1022,
			Process_Notes: 10472,
			Process_Session: 4710,
			Product: 1024,
			Product_Inventory: 10566,
			Profile_Album: 10308,
			Project: 10473,
			Project_Service_Approval: 10434,
			Project_Team_Member: 10481,
			Purchase_Order: 10567,
			Purchase_Order_Bill: 10568,
			Purchase_Order_Product: 10569,
			Purchase_Order_Receipt: 10570,
			Purchase_Order_Receipt_Product: 10571,
			Purchase_Order_SubStatus: 10572,
			Quote: 1084,
			Quote_Booking_Incident: 10573,
			Quote_Booking_Product: 10574,
			Quote_Booking_Service: 10575,
			Quote_Booking_Service_Task: 10576,
			Recurring_Appointment: 4251,
			Resource_Group: 4007,
			Resource_Restriction_Deprecated: 10601,
			Resource_Territory: 10423,
			RMA: 10581,
			RMA_Product: 10582,
			RMA_Receipt: 10583,
			RMA_Receipt_Product: 10584,
			RMA_SubStatus: 10585,
			RTV: 10586,
			RTV_Product: 10587,
			RTV_Substatus: 10588,
			Scheduling_Group: 4005,
			Sequence: 10273,
			Sequence_Target: 10275,
			Service_Activity: 4214,
			Session: 10721,
			Ship_Via: 10590,
			Social_Activity: 4216,
			Social_Profile: 99,
			Suggestion: 10289,
			System_User_Scheduler_Setting: 10426,
			Task: 4212,
			Tax_Code: 10591,
			Team: 9,
			Territory: 2013,
			Time_Group_Detail: 10428,
			Time_Off_Request: 10593,
			Toolbar_Button: 10846,
			User: 8,
			Warehouse: 10595,
			Work_Order: 10596,
			Work_Order_Characteristic_Deprecated: 10597,
			Work_Order_Incident: 10599,
			Work_Order_Product: 10600,
			Work_Order_Service: 10602,
			Work_Order_Service_Task: 10603
		},
		StateCode : {
			Active: 0,
			Inactive: 1
		},
		StatusCode : {
			Active: 1,
			Inactive: 2
		},
		RollupState : {
			NotCalculated: 0,
			Calculated: 1,
			OverflowError: 2,
			OtherError: 3,
			RetryLimitExceeded: 4,
			HierarchicalRecursionLimitReached: 5,
			LoopDetected: 6
		}
	};
})(OptionSet || (OptionSet = {}));