<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Exe</OutputType>
		<IsPublishable>True</IsPublishable>

		<AssemblyVersion>4.12.34.56</AssemblyVersion>
		<FileVersion>4.12.34.56</FileVersion>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<RepositoryUrl>https://github.com/phuocle/Dynamics-Crm-DevKit</RepositoryUrl>
		<Company>PhuocLe</Company>
		<Product>DynamicsCrm.DevKit.Tool</Product>
		<Copyright>Copyright © PhuocLe 2016 - 2036</Copyright>
		<PackageProjectUrl>https://github.com/phuocle/Dynamics-Crm-DevKit</PackageProjectUrl>
		<Version>4.12.34.56</Version>
		<AssemblyTitle>DynamicsCrm.DevKit.Tool</AssemblyTitle>
		<AssemblyDescription>DynamicsCrm.DevKit.Tool</AssemblyDescription>
		<BaseOutputPath>bin</BaseOutputPath>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<PlatformTarget>x86</PlatformTarget>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<PlatformTarget>x86</PlatformTarget>
		<DefineConstants>TRACE</DefineConstants>

	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Nuget\**" />
	  <EmbeddedResource Remove="Nuget\**" />
	  <None Remove="Nuget\**" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="images\icon.png" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="docs\README.md" />
	  <None Include="Nuget\DynamicsCrm.DevKit.Tool.nuspec" />
	  <None Include="Nuget\pack.bat" />
	  <None Include="license\LICENSE.txt" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="CmdLine" Version="1.0.7.509" />
	  <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="*" />
	  <PackageReference Include="Microsoft.CrmSdk.Workflow" Version="*" />
	  <PackageReference Include="Microsoft.CrmSdk.XrmTooling.CoreAssembly" Version="*" />
	  <PackageReference Include="NUglify" Version="1.21.17" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="Microsoft.VisualStudio.Coverage.Analysis">
	    <HintPath>lib\Microsoft.VisualStudio.Coverage.Analysis.dll</HintPath>
	    <SpecificVersion>False</SpecificVersion>
	  </Reference>
	</ItemGroup>
</Project>