// @ts-nocheck
/** @namespace DevKitDialog */
var DevKitDialog;
(function (DevKitDialog) {
	'use strict';
	/** @class */
	DevKitDialog.pl_dataversedialogbuilder_demo = function (executionContext, defaultWebResourceName) {
		return new devKit.LoadFormDialog(executionContext, [
			"pl_header_label1",
			"pl_header_label2",
			"pl_label1",
			"pl_label2",
			"pl_label3",
			"pl_label4",
			"pl_label5",
			"pl_label6",
			"pl_label7",
			"pl_label8",
			"pl_label9",
			"pl_label10",
			"pl_label11",
			"pl_label12",
			"pl_label13",
			"pl_label14",
			"pl_label15",
			"pl_label16",
			"pl_label17",
			"pl_label18",
			"pl_label19",
			"pl_label20",
			"pl_label_hide",
			"pl_textbox1",
			"pl_textbox2",
			"pl_textbox3",
			"pl_textbox4",
			"pl_textbox5",
			"pl_textbox_hide",
			"pl_textarea1",
			"pl_textarea_hide",
			"pl_datetime1",
			"pl_datetime2",
			"pl_datetime3",
			"pl_datetime_hide",
			"pl_number1",
			"pl_number2",
			"pl_number3",
			"pl_number4",
			"pl_number_hide",
			"pl_lookup1",
			"pl_lookup2",
			"pl_lookup_hide",
			"pl_regarding1",
			"pl_regarding_hide",
			"pl_iframe1",
			"pl_iframe_hide",
			"pl_dropdown1",
			"pl_dropdown2",
			"pl_dropdown3",
			"pl_dropdown_hide",
			"pl_optionset1",
			"pl_optionset2",
			"pl_optionset3",
			"pl_optionset4",
			"pl_optionset5",
			"pl_optionset6",
			"pl_optionset_hide",
			"pl_twooptions1",
			"pl_twooptions2",
			"pl_twooptions3",
			"pl_twooptions_hide",
			"pl_subgrid1",
			"pl_subgrid_hide",
			"pl_chart1",
			"pl_chart_hide",
			"pl_rtb1",
			"pl_rtb2",
			"pl_rtb_hide",
			"pl_entity_optionset1",
			"pl_entity_optionset_hide",
			"pl_advfind1",
			"pl_advfind_hide",
			"pl_advfind_result1",
			"pl_advfind_result_hide",
			"pl_upload1",
			"pl_upload_hide",
			"pl_advfind_and_result1",
			"pl_advfind_and_result_hide",
			"pl_multiselect_lookup1",
			"pl_multiselect_lookup_hide",
			"pl_parameter_input",
			"pl_para_fetchxml",
			"pl_para_entitylogicalname",
			"pl_para_validationerrormessage",
			"pl_para_isvalid",
			"pl_para_layout_xml",
			"pl_para_selected_records",
			"pl_para_entity_type",
			"pl_para_attachment_file_name",
			"pl_para_uploaded_file_size",
			"pl_para_entity_records",
			"pl_para_targetentities",
			"pl_para_selectedentities",
			"pl_para_isdisabled",
			"pl_para_disablemru"
		], defaultWebResourceName);
	};
})(DevKitDialog || (DevKitDialog = {}));
