using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

[assembly: AssemblyTitle("Dev.DevKit.WebResourceTs")]
[assembly: AssemblyDescription("Generated by DynamicsCrm.DevKit - v.4.12.34.56 - Build: 09.01.2026 13:09:31 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Dev.DevKit.WebResourceTs")]
[assembly: AssemblyCopyright("Copyright © 2026")]
[assembly: AssemblyTrademark("")]
[assembly: SecurityRules(SecurityRuleSet.Level2)]
[assembly: ComVisible(false)]
[assembly: Guid("fdf536f3-145b-449a-8eda-fb0278c956fa")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
