'use strict';
/** @namespace DevKit */
var DevKit;
(function (DevKit) {
	'use strict';
	DevKit.FormBieu_mau_nguoi_dung_Doanh_nghiep = function(executionContext, defaultWebResourceName) {
		var formContext = null;
		if (executionContext !== undefined) {
			if (executionContext.getFormContext === undefined) {
				formContext = executionContext;
			}
			else {
				formContext = executionContext.getFormContext();
			}
		}
		var form = devKit.LoadForm(formContext);
		var body = {
			AccessMode: {},
			Address1_Composite: {},
			Address1_Telephone1: {},
			BusinessUnitId: {},
			CALType: {},
			DefaultMailbox: {},
			DirectReports: {},
			DomainName: {},
			FullName: {},
			InternalEMailAddress: {},
			InviteStatusCode: {},
			MobilePhone: {},
			ParentSystemUserId: {},
			PreferredAddressCode: {},
			TeamsSubGrid: {},
			Title: {},
			WindowsLiveID: {}
		};
		devKit.LoadFields(formContext, body);
		var tab = {
			ADMINISTRATION_TAB: {
				Section: {
					administration: {},
					e_mail_configuration: {}
				}
			},
			SUMMARY_TAB: {
				Section: {
					DirectReports: {},
					mailing_address: {},
					online_account_information: {},
					onpremise_account_information: {},
					organization_information: {},
					TEAMS_TAB: {},
					user_information: {}
				}
			}
		};
		devKit.LoadTabs(formContext, tab);
		body.Tab = tab;
		form.Body = body;
		var grid = {
			DirectReports: {},
			TeamsSubGrid: {},
		};
		devKit.LoadGrids(formContext, grid);
		form.Grid = grid;
		var navigation = {
			adx_inviteredemption_systemuser_owninguser: {},
			adx_portalcomment_systemuser_owninguser: {},
			adx_webformsession_systemuser: {},
			AIPluginUserSetting_SystemUser_Syst: {},
			bizmap_systemuser_businessid: {},
			contact_owning_user: {},
			email_acceptingentity_systemuser: {},
			flowmachinegroup_PasswordChangedBy: {},
			flowmachinegroup_RotationStartedBy: {},
			knowledgearticle_primaryauthorid: {},
			lk_audit_callinguserid: {},
			lk_audit_userid: {},
			lk_feedback_closedby: {},
			lk_queueitembase_workerid: {},
			lk_teambase_administratorid: {},
			mailbox_regarding_systemuser: {},
			mspp_systemuser_mspp_adplacement_createdby: {},
			mspp_systemuser_mspp_adplacement_modifiedby: {},
			mspp_systemuser_mspp_columnpermission_createdby: {},
			mspp_systemuser_mspp_columnpermission_modifiedby: {},
			mspp_systemuser_mspp_columnpermissionprofile_createdby: {},
			mspp_systemuser_mspp_columnpermissionprofile_modifiedby: {},
			mspp_systemuser_mspp_contentsnippet_createdby: {},
			mspp_systemuser_mspp_contentsnippet_modifiedby: {},
			mspp_systemuser_mspp_entityform_createdby: {},
			mspp_systemuser_mspp_entityform_modifiedby: {},
			mspp_systemuser_mspp_entityformmetadata_createdby: {},
			mspp_systemuser_mspp_entityformmetadata_modifiedby: {},
			mspp_systemuser_mspp_entitylist_createdby: {},
			mspp_systemuser_mspp_entitylist_modifiedby: {},
			mspp_systemuser_mspp_entitypermission_createdby: {},
			mspp_systemuser_mspp_entitypermission_modifiedby: {},
			mspp_systemuser_mspp_pagetemplate_createdby: {},
			mspp_systemuser_mspp_pagetemplate_modifiedby: {},
			mspp_systemuser_mspp_pollplacement_createdby: {},
			mspp_systemuser_mspp_pollplacement_modifiedby: {},
			mspp_systemuser_mspp_publishingstate_createdby: {},
			mspp_systemuser_mspp_publishingstate_modifiedby: {},
			mspp_systemuser_mspp_publishingstatetransitionrule_createdby: {},
			mspp_systemuser_mspp_publishingstatetransitionrule_modifiedby: {},
			mspp_systemuser_mspp_redirect_createdby: {},
			mspp_systemuser_mspp_redirect_modifiedby: {},
			mspp_systemuser_mspp_shortcut_createdby: {},
			mspp_systemuser_mspp_shortcut_modifiedby: {},
			mspp_systemuser_mspp_sitemarker_createdby: {},
			mspp_systemuser_mspp_sitemarker_modifiedby: {},
			mspp_systemuser_mspp_sitesetting_createdby: {},
			mspp_systemuser_mspp_sitesetting_modifiedby: {},
			mspp_systemuser_mspp_webfile_createdby: {},
			mspp_systemuser_mspp_webfile_modifiedby: {},
			mspp_systemuser_mspp_webform_createdby: {},
			mspp_systemuser_mspp_webform_modifiedby: {},
			mspp_systemuser_mspp_webformmetadata_createdby: {},
			mspp_systemuser_mspp_webformmetadata_modifiedby: {},
			mspp_systemuser_mspp_webformstep_createdby: {},
			mspp_systemuser_mspp_webformstep_modifiedby: {},
			mspp_systemuser_mspp_weblink_createdby: {},
			mspp_systemuser_mspp_weblink_modifiedby: {},
			mspp_systemuser_mspp_weblinkset_createdby: {},
			mspp_systemuser_mspp_weblinkset_modifiedby: {},
			mspp_systemuser_mspp_webpage_createdby: {},
			mspp_systemuser_mspp_webpage_modifiedby: {},
			mspp_systemuser_mspp_webpageaccesscontrolrule_createdby: {},
			mspp_systemuser_mspp_webpageaccesscontrolrule_modifiedby: {},
			mspp_systemuser_mspp_webrole_createdby: {},
			mspp_systemuser_mspp_webrole_modifiedby: {},
			mspp_systemuser_mspp_website_createdby: {},
			mspp_systemuser_mspp_website_modifiedby: {},
			mspp_systemuser_mspp_websiteaccess_createdby: {},
			mspp_systemuser_mspp_websiteaccess_modifiedby: {},
			mspp_systemuser_mspp_websitelanguage_createdby: {},
			mspp_systemuser_mspp_websitelanguage_modifiedby: {},
			mspp_systemuser_mspp_webtemplate_createdby: {},
			mspp_systemuser_mspp_webtemplate_modifiedby: {},
			privilegecheckerlog_CheckedUser_systemuser: {},
			privilegecheckerlog_ImpersonatingUser_systemuser: {},
			privilegecheckerlog_SupportingCaller_systemuser: {},
			queue_primary_user: {},
			sideloadedaiplugin_sideloadedpluginownerid: {},
			system_user_accounts: {},
			system_user_contacts: {},
			system_user_email_templates: {},
			system_user_territories: {},
			system_user_workflow: {},
			systemuser_appusersetting_userId: {},
			systemuser_bot_publishedby: {},
			SystemUser_Email_EmailSender: {},
			SystemUser_ExternalPartyItems: {},
			systemuser_internal_addresses: {},
			user_accounts: {},
			user_activityfileattachment: {},
			user_adx_invitation: {},
			user_adx_setting: {},
			user_aiplugin: {},
			user_aipluginauth: {},
			user_aipluginconversationstarter: {},
			user_aipluginconversationstartermapping: {},
			user_aipluginexternalschema: {},
			user_aipluginexternalschemaproperty: {},
			user_aiplugingovernance: {},
			user_aiplugingovernanceext: {},
			user_aiplugininstance: {},
			user_aipluginoperation: {},
			user_aipluginoperationparameter: {},
			user_aipluginoperationresponsetemplate: {},
			user_aipluginusersetting: {},
			user_appnotification: {},
			user_appointment: {},
			user_archivecleanupinfo: {},
			user_archivecleanupoperation: {},
			user_bot: {},
			user_botcomponent: {},
			user_botcomponentcollection: {},
			user_bulkarchiveconfig: {},
			user_bulkarchivefailuredetail: {},
			user_bulkarchiveoperation: {},
			user_canvasappextendedmetadata: {},
			user_card: {},
			user_channelaccessprofile: {},
			user_comment: {},
			user_componentversion: {},
			user_connectioninstance: {},
			user_connectionreference: {},
			user_connector: {},
			user_conversationtranscript: {},
			user_convertrule: {},
			user_copilotglossaryterm: {},
			user_copilotsynonyms: {},
			user_credential: {},
			user_customapi: {},
			user_datalakefolder: {},
			user_desktopflowbinary: {},
			user_desktopflowmodule: {},
			user_dvfilesearch: {},
			user_dvfilesearchattribute: {},
			user_dvfilesearchentity: {},
			user_dvtablesearch: {},
			user_dvtablesearchattribute: {},
			user_dvtablesearchentity: {},
			user_email: {},
			user_enablearchivalrequest: {},
			user_environmentvariabledefinition: {},
			user_environmentvariablevalue: {},
			user_exchangesyncidmapping: {},
			user_exportedexcel: {},
			user_exportsolutionupload: {},
			user_externalparty: {},
			user_fabricaiskill: {},
			user_featurecontrolsetting: {},
			user_federatedknowledgeconfiguration: {},
			user_federatedknowledgeentityconfiguration: {},
			user_flowcapacityassignment: {},
			user_flowcredentialapplication: {},
			user_flowevent: {},
			user_flowmachine: {},
			user_flowmachinegroup: {},
			user_flowmachineimage: {},
			user_flowmachineimageversion: {},
			user_flowmachinenetwork: {},
			user_flowrun: {},
			user_flowsession: {},
			user_fxexpression: {},
			user_goal: {},
			user_goal_goalowner: {},
			user_interactionforemail: {},
			user_keyvaultreference: {},
			user_knowledgearticle: {},
			user_mailbox: {},
			user_managedidentity: {},
			user_msdyn_aibdataset: {},
			user_msdyn_aibdatasetfile: {},
			user_msdyn_aibdatasetrecord: {},
			user_msdyn_aibdatasetscontainer: {},
			user_msdyn_aibfeedbackloop: {},
			user_msdyn_aibfile: {},
			user_msdyn_aibfileattacheddata: {},
			user_msdyn_aievent: {},
			user_msdyn_aifptrainingdocument: {},
			user_msdyn_aimodel: {},
			user_msdyn_aiodimage: {},
			user_msdyn_aiodlabel: {},
			user_msdyn_aiodtrainingboundingbox: {},
			user_msdyn_aiodtrainingimage: {},
			user_msdyn_aitemplate: {},
			user_msdyn_analysiscomponent: {},
			user_msdyn_analysisjob: {},
			user_msdyn_analysisoverride: {},
			user_msdyn_analysisresult: {},
			user_msdyn_analysisresultdetail: {},
			user_msdyn_customcontrolextendedsettings: {},
			user_msdyn_dataflow: {},
			user_msdyn_dataflow_datalakefolder: {},
			user_msdyn_dataflowconnectionreference: {},
			user_msdyn_dataflowrefreshhistory: {},
			user_msdyn_dataflowtemplate: {},
			user_msdyn_dmsrequest: {},
			user_msdyn_dmsrequeststatus: {},
			user_msdyn_dmssyncrequest: {},
			user_msdyn_dmssyncstatus: {},
			user_msdyn_entitylinkchatconfiguration: {},
			user_msdyn_entityrefreshhistory: {},
			user_msdyn_favoriteknowledgearticle: {},
			user_msdyn_federatedarticle: {},
			user_msdyn_fileupload: {},
			user_msdyn_flow_actionapprovalmodel: {},
			user_msdyn_flow_approval: {},
			user_msdyn_flow_approvalrequest: {},
			user_msdyn_flow_approvalresponse: {},
			user_msdyn_flow_approvalstep: {},
			user_msdyn_flow_awaitallactionapprovalmodel: {},
			user_msdyn_flow_awaitallapprovalmodel: {},
			user_msdyn_flow_basicapprovalmodel: {},
			user_msdyn_flow_flowapproval: {},
			user_msdyn_integratedsearchprovider: {},
			user_msdyn_kalanguagesetting: {},
			user_msdyn_kbattachment: {},
			user_msdyn_kmfederatedsearchconfig: {},
			user_msdyn_knowledgearticleimage: {},
			user_msdyn_knowledgearticletemplate: {},
			user_msdyn_knowledgeassetconfiguration: {},
			user_msdyn_knowledgeinteractioninsight: {},
			user_msdyn_knowledgemanagementsetting: {},
			user_msdyn_knowledgepersonalfilter: {},
			user_msdyn_knowledgesearchfilter: {},
			user_msdyn_knowledgesearchinsight: {},
			user_msdyn_mobileapp: {},
			user_msdyn_pmanalysishistory: {},
			user_msdyn_pmbusinessruleautomationconfig: {},
			user_msdyn_pmcalendar: {},
			user_msdyn_pmcalendarversion: {},
			user_msdyn_pminferredtask: {},
			user_msdyn_pmprocessextendedmetadataversion: {},
			user_msdyn_pmprocesstemplate: {},
			user_msdyn_pmprocessusersettings: {},
			user_msdyn_pmprocessversion: {},
			user_msdyn_pmrecording: {},
			user_msdyn_pmsimulation: {},
			user_msdyn_pmtemplate: {},
			user_msdyn_pmview: {},
			user_msdyn_richtextfile: {},
			user_msdyn_salesforcestructuredobject: {},
			user_msdyn_salesforcestructuredqnaconfig: {},
			user_msdyn_schedule: {},
			user_msdyn_serviceconfiguration: {},
			user_msdyn_slakpi: {},
			user_msdyn_solutionhealthrule: {},
			user_msdyn_solutionhealthruleargument: {},
			user_msdyn_virtualtablecolumncandidate: {},
			user_msdynce_botcontent: {},
			user_mspcat_catalogsubmissionfiles: {},
			user_mspcat_packagestore: {},
			user_nlsqregistration: {},
			user_parent_user: {},
			user_pdfsetting: {},
			user_phonecall: {},
			user_plannerbusinessscenario: {},
			user_plannersyncaction: {},
			user_powerbidataset: {},
			user_powerbidatasetapdx: {},
			user_powerbimashupparameter: {},
			user_powerbireport: {},
			user_powerbireportapdx: {},
			user_powerfxrule: {},
			user_powerpagecomponent: {},
			user_powerpagesite: {},
			user_powerpagesitelanguage: {},
			user_powerpagesitepublished: {},
			user_powerpageslog: {},
			user_powerpagesscanreport: {},
			user_privilegecheckerrun: {},
			user_processstageparameter: {},
			user_profilerule: {},
			user_recentlyused: {},
			user_reconciliationentityinfo: {},
			user_reconciliationentitystepinfo: {},
			user_reconciliationinfo: {},
			user_retaineddataexcel: {},
			user_retentioncleanupinfo: {},
			user_retentioncleanupoperation: {},
			user_retentionconfig: {},
			user_retentionfailuredetail: {},
			user_retentionoperation: {},
			user_routingrule: {},
			user_routingruleitem: {},
			user_settings: {},
			user_sharepointsite: {},
			user_sideloadedaiplugin: {},
			user_slabase: {},
			user_solutioncomponentbatchconfiguration: {},
			user_stagesolutionupload: {},
			user_synapsedatabase: {},
			user_task: {},
			user_tdsmetadata: {},
			user_untrackedemail: {},
			user_userauthztracker: {},
			user_workflowbinary: {},
			user_workqueue: {},
			user_workqueueitem: {},
			workqueueitem_processinguser: {}
		};
		devKit.LoadNavigations(formContext, navigation);
		form.Navigation = navigation;
		form.Utility = devKit.LoadUtility(defaultWebResourceName);
		form.ExecutionContext = devKit.LoadExecutionContext(executionContext);
		devKit.LoadOthers(formContext, form, defaultWebResourceName);
		return form;
	};
	DevKit.FormNguoi_dung = function(executionContext, defaultWebResourceName) {
		var formContext = null;
		if (executionContext !== undefined) {
			if (executionContext.getFormContext === undefined) {
				formContext = executionContext;
			}
			else {
				formContext = executionContext.getFormContext();
			}
		}
		var form = devKit.LoadForm(formContext);
		var body = {
			AccessMode: {},
			Address1_Composite: {},
			Address1_Fax: {},
			Address1_Telephone1: {},
			Address1_Telephone2: {},
			Address1_Telephone3: {},
			Address2_Composite: {},
			BusinessUnitId: {},
			CALType: {},
			DefaultMailbox: {},
			DirectReports: {},
			DomainName: {},
			FullName: {},
			HomePhone: {},
			InternalEMailAddress: {},
			InviteStatusCode: {},
			MobileAlertEMail: {},
			MobileOfflineProfileId: {},
			MobilePhone: {},
			notescontrol: {},
			ParentSystemUserId: {},
			PersonalEMailAddress: {},
			PositionId: {},
			PreferredAddressCode: {},
			PreferredPhoneCode: {},
			PrivateQueuesSubGrid: {},
			QueueId: {},
			TeamsSubGrid: {},
			Title: {},
			WindowsLiveID: {}
		};
		devKit.LoadFields(formContext, body);
		var tab = {
			ADMINISTRATION_TAB: {
				Section: {
					administration: {},
					e_mail_configuration: {}
				}
			},
			DETAILS_TAB: {
				Section: {
					DirectReports: {},
					mailing_address: {},
					user_information_2: {}
				}
			},
			MobileOfflineProfile_TAB: {
				Section: {
					mobileofflineaccessinfo: {}
				}
			},
			SUMMARY_TAB: {
				Section: {
					online_account_information: {},
					onpremise_account_information: {},
					organization_information: {},
					queue_information: {},
					queue_selection: {},
					SOCIAL_PANE_TAB: {},
					teams_information: {},
					user_information: {}
				}
			}
		};
		devKit.LoadTabs(formContext, tab);
		body.Tab = tab;
		form.Body = body;
		var grid = {
			DirectReports: {},
			PrivateQueuesSubGrid: {},
			TeamsSubGrid: {},
		};
		devKit.LoadGrids(formContext, grid);
		form.Grid = grid;
		var navigation = {
			adx_inviteredemption_systemuser_owninguser: {},
			adx_portalcomment_systemuser_owninguser: {},
			adx_webformsession_systemuser: {},
			AIPluginUserSetting_SystemUser_Syst: {},
			bizmap_systemuser_businessid: {},
			contact_owning_user: {},
			email_acceptingentity_systemuser: {},
			flowmachinegroup_PasswordChangedBy: {},
			flowmachinegroup_RotationStartedBy: {},
			knowledgearticle_primaryauthorid: {},
			lk_audit_callinguserid: {},
			lk_audit_userid: {},
			lk_feedback_closedby: {},
			lk_queueitembase_workerid: {},
			lk_teambase_administratorid: {},
			mailbox_regarding_systemuser: {},
			mspp_systemuser_mspp_adplacement_createdby: {},
			mspp_systemuser_mspp_adplacement_modifiedby: {},
			mspp_systemuser_mspp_columnpermission_createdby: {},
			mspp_systemuser_mspp_columnpermission_modifiedby: {},
			mspp_systemuser_mspp_columnpermissionprofile_createdby: {},
			mspp_systemuser_mspp_columnpermissionprofile_modifiedby: {},
			mspp_systemuser_mspp_contentsnippet_createdby: {},
			mspp_systemuser_mspp_contentsnippet_modifiedby: {},
			mspp_systemuser_mspp_entityform_createdby: {},
			mspp_systemuser_mspp_entityform_modifiedby: {},
			mspp_systemuser_mspp_entityformmetadata_createdby: {},
			mspp_systemuser_mspp_entityformmetadata_modifiedby: {},
			mspp_systemuser_mspp_entitylist_createdby: {},
			mspp_systemuser_mspp_entitylist_modifiedby: {},
			mspp_systemuser_mspp_entitypermission_createdby: {},
			mspp_systemuser_mspp_entitypermission_modifiedby: {},
			mspp_systemuser_mspp_pagetemplate_createdby: {},
			mspp_systemuser_mspp_pagetemplate_modifiedby: {},
			mspp_systemuser_mspp_pollplacement_createdby: {},
			mspp_systemuser_mspp_pollplacement_modifiedby: {},
			mspp_systemuser_mspp_publishingstate_createdby: {},
			mspp_systemuser_mspp_publishingstate_modifiedby: {},
			mspp_systemuser_mspp_publishingstatetransitionrule_createdby: {},
			mspp_systemuser_mspp_publishingstatetransitionrule_modifiedby: {},
			mspp_systemuser_mspp_redirect_createdby: {},
			mspp_systemuser_mspp_redirect_modifiedby: {},
			mspp_systemuser_mspp_shortcut_createdby: {},
			mspp_systemuser_mspp_shortcut_modifiedby: {},
			mspp_systemuser_mspp_sitemarker_createdby: {},
			mspp_systemuser_mspp_sitemarker_modifiedby: {},
			mspp_systemuser_mspp_sitesetting_createdby: {},
			mspp_systemuser_mspp_sitesetting_modifiedby: {},
			mspp_systemuser_mspp_webfile_createdby: {},
			mspp_systemuser_mspp_webfile_modifiedby: {},
			mspp_systemuser_mspp_webform_createdby: {},
			mspp_systemuser_mspp_webform_modifiedby: {},
			mspp_systemuser_mspp_webformmetadata_createdby: {},
			mspp_systemuser_mspp_webformmetadata_modifiedby: {},
			mspp_systemuser_mspp_webformstep_createdby: {},
			mspp_systemuser_mspp_webformstep_modifiedby: {},
			mspp_systemuser_mspp_weblink_createdby: {},
			mspp_systemuser_mspp_weblink_modifiedby: {},
			mspp_systemuser_mspp_weblinkset_createdby: {},
			mspp_systemuser_mspp_weblinkset_modifiedby: {},
			mspp_systemuser_mspp_webpage_createdby: {},
			mspp_systemuser_mspp_webpage_modifiedby: {},
			mspp_systemuser_mspp_webpageaccesscontrolrule_createdby: {},
			mspp_systemuser_mspp_webpageaccesscontrolrule_modifiedby: {},
			mspp_systemuser_mspp_webrole_createdby: {},
			mspp_systemuser_mspp_webrole_modifiedby: {},
			mspp_systemuser_mspp_website_createdby: {},
			mspp_systemuser_mspp_website_modifiedby: {},
			mspp_systemuser_mspp_websiteaccess_createdby: {},
			mspp_systemuser_mspp_websiteaccess_modifiedby: {},
			mspp_systemuser_mspp_websitelanguage_createdby: {},
			mspp_systemuser_mspp_websitelanguage_modifiedby: {},
			mspp_systemuser_mspp_webtemplate_createdby: {},
			mspp_systemuser_mspp_webtemplate_modifiedby: {},
			privilegecheckerlog_CheckedUser_systemuser: {},
			privilegecheckerlog_ImpersonatingUser_systemuser: {},
			privilegecheckerlog_SupportingCaller_systemuser: {},
			queue_primary_user: {},
			sideloadedaiplugin_sideloadedpluginownerid: {},
			system_user_accounts: {},
			system_user_contacts: {},
			system_user_email_templates: {},
			system_user_territories: {},
			system_user_workflow: {},
			systemuser_appusersetting_userId: {},
			systemuser_bot_publishedby: {},
			SystemUser_Email_EmailSender: {},
			SystemUser_ExternalPartyItems: {},
			systemuser_internal_addresses: {},
			user_accounts: {},
			user_activityfileattachment: {},
			user_adx_invitation: {},
			user_adx_setting: {},
			user_aiplugin: {},
			user_aipluginauth: {},
			user_aipluginconversationstarter: {},
			user_aipluginconversationstartermapping: {},
			user_aipluginexternalschema: {},
			user_aipluginexternalschemaproperty: {},
			user_aiplugingovernance: {},
			user_aiplugingovernanceext: {},
			user_aiplugininstance: {},
			user_aipluginoperation: {},
			user_aipluginoperationparameter: {},
			user_aipluginoperationresponsetemplate: {},
			user_aipluginusersetting: {},
			user_appnotification: {},
			user_appointment: {},
			user_archivecleanupinfo: {},
			user_archivecleanupoperation: {},
			user_bot: {},
			user_botcomponent: {},
			user_botcomponentcollection: {},
			user_bulkarchiveconfig: {},
			user_bulkarchivefailuredetail: {},
			user_bulkarchiveoperation: {},
			user_canvasappextendedmetadata: {},
			user_card: {},
			user_channelaccessprofile: {},
			user_comment: {},
			user_componentversion: {},
			user_connectioninstance: {},
			user_connectionreference: {},
			user_connector: {},
			user_conversationtranscript: {},
			user_convertrule: {},
			user_copilotglossaryterm: {},
			user_copilotsynonyms: {},
			user_credential: {},
			user_customapi: {},
			user_datalakefolder: {},
			user_desktopflowbinary: {},
			user_desktopflowmodule: {},
			user_dvfilesearch: {},
			user_dvfilesearchattribute: {},
			user_dvfilesearchentity: {},
			user_dvtablesearch: {},
			user_dvtablesearchattribute: {},
			user_dvtablesearchentity: {},
			user_email: {},
			user_enablearchivalrequest: {},
			user_environmentvariabledefinition: {},
			user_environmentvariablevalue: {},
			user_exchangesyncidmapping: {},
			user_exportedexcel: {},
			user_exportsolutionupload: {},
			user_externalparty: {},
			user_fabricaiskill: {},
			user_featurecontrolsetting: {},
			user_federatedknowledgeconfiguration: {},
			user_federatedknowledgeentityconfiguration: {},
			user_flowcapacityassignment: {},
			user_flowcredentialapplication: {},
			user_flowevent: {},
			user_flowmachine: {},
			user_flowmachinegroup: {},
			user_flowmachineimage: {},
			user_flowmachineimageversion: {},
			user_flowmachinenetwork: {},
			user_flowrun: {},
			user_flowsession: {},
			user_fxexpression: {},
			user_goal: {},
			user_goal_goalowner: {},
			user_interactionforemail: {},
			user_keyvaultreference: {},
			user_knowledgearticle: {},
			user_mailbox: {},
			user_managedidentity: {},
			user_msdyn_aibdataset: {},
			user_msdyn_aibdatasetfile: {},
			user_msdyn_aibdatasetrecord: {},
			user_msdyn_aibdatasetscontainer: {},
			user_msdyn_aibfeedbackloop: {},
			user_msdyn_aibfile: {},
			user_msdyn_aibfileattacheddata: {},
			user_msdyn_aievent: {},
			user_msdyn_aifptrainingdocument: {},
			user_msdyn_aimodel: {},
			user_msdyn_aiodimage: {},
			user_msdyn_aiodlabel: {},
			user_msdyn_aiodtrainingboundingbox: {},
			user_msdyn_aiodtrainingimage: {},
			user_msdyn_aitemplate: {},
			user_msdyn_analysiscomponent: {},
			user_msdyn_analysisjob: {},
			user_msdyn_analysisoverride: {},
			user_msdyn_analysisresult: {},
			user_msdyn_analysisresultdetail: {},
			user_msdyn_customcontrolextendedsettings: {},
			user_msdyn_dataflow: {},
			user_msdyn_dataflow_datalakefolder: {},
			user_msdyn_dataflowconnectionreference: {},
			user_msdyn_dataflowrefreshhistory: {},
			user_msdyn_dataflowtemplate: {},
			user_msdyn_dmsrequest: {},
			user_msdyn_dmsrequeststatus: {},
			user_msdyn_dmssyncrequest: {},
			user_msdyn_dmssyncstatus: {},
			user_msdyn_entitylinkchatconfiguration: {},
			user_msdyn_entityrefreshhistory: {},
			user_msdyn_favoriteknowledgearticle: {},
			user_msdyn_federatedarticle: {},
			user_msdyn_fileupload: {},
			user_msdyn_flow_actionapprovalmodel: {},
			user_msdyn_flow_approval: {},
			user_msdyn_flow_approvalrequest: {},
			user_msdyn_flow_approvalresponse: {},
			user_msdyn_flow_approvalstep: {},
			user_msdyn_flow_awaitallactionapprovalmodel: {},
			user_msdyn_flow_awaitallapprovalmodel: {},
			user_msdyn_flow_basicapprovalmodel: {},
			user_msdyn_flow_flowapproval: {},
			user_msdyn_integratedsearchprovider: {},
			user_msdyn_kalanguagesetting: {},
			user_msdyn_kbattachment: {},
			user_msdyn_kmfederatedsearchconfig: {},
			user_msdyn_knowledgearticleimage: {},
			user_msdyn_knowledgearticletemplate: {},
			user_msdyn_knowledgeassetconfiguration: {},
			user_msdyn_knowledgeinteractioninsight: {},
			user_msdyn_knowledgemanagementsetting: {},
			user_msdyn_knowledgepersonalfilter: {},
			user_msdyn_knowledgesearchfilter: {},
			user_msdyn_knowledgesearchinsight: {},
			user_msdyn_mobileapp: {},
			user_msdyn_pmanalysishistory: {},
			user_msdyn_pmbusinessruleautomationconfig: {},
			user_msdyn_pmcalendar: {},
			user_msdyn_pmcalendarversion: {},
			user_msdyn_pminferredtask: {},
			user_msdyn_pmprocessextendedmetadataversion: {},
			user_msdyn_pmprocesstemplate: {},
			user_msdyn_pmprocessusersettings: {},
			user_msdyn_pmprocessversion: {},
			user_msdyn_pmrecording: {},
			user_msdyn_pmsimulation: {},
			user_msdyn_pmtemplate: {},
			user_msdyn_pmview: {},
			user_msdyn_richtextfile: {},
			user_msdyn_salesforcestructuredobject: {},
			user_msdyn_salesforcestructuredqnaconfig: {},
			user_msdyn_schedule: {},
			user_msdyn_serviceconfiguration: {},
			user_msdyn_slakpi: {},
			user_msdyn_solutionhealthrule: {},
			user_msdyn_solutionhealthruleargument: {},
			user_msdyn_virtualtablecolumncandidate: {},
			user_msdynce_botcontent: {},
			user_mspcat_catalogsubmissionfiles: {},
			user_mspcat_packagestore: {},
			user_nlsqregistration: {},
			user_parent_user: {},
			user_pdfsetting: {},
			user_phonecall: {},
			user_plannerbusinessscenario: {},
			user_plannersyncaction: {},
			user_powerbidataset: {},
			user_powerbidatasetapdx: {},
			user_powerbimashupparameter: {},
			user_powerbireport: {},
			user_powerbireportapdx: {},
			user_powerfxrule: {},
			user_powerpagecomponent: {},
			user_powerpagesite: {},
			user_powerpagesitelanguage: {},
			user_powerpagesitepublished: {},
			user_powerpageslog: {},
			user_powerpagesscanreport: {},
			user_privilegecheckerrun: {},
			user_processstageparameter: {},
			user_profilerule: {},
			user_recentlyused: {},
			user_reconciliationentityinfo: {},
			user_reconciliationentitystepinfo: {},
			user_reconciliationinfo: {},
			user_retaineddataexcel: {},
			user_retentioncleanupinfo: {},
			user_retentioncleanupoperation: {},
			user_retentionconfig: {},
			user_retentionfailuredetail: {},
			user_retentionoperation: {},
			user_routingrule: {},
			user_routingruleitem: {},
			user_settings: {},
			user_sharepointsite: {},
			user_sideloadedaiplugin: {},
			user_slabase: {},
			user_solutioncomponentbatchconfiguration: {},
			user_stagesolutionupload: {},
			user_synapsedatabase: {},
			user_task: {},
			user_tdsmetadata: {},
			user_untrackedemail: {},
			user_userauthztracker: {},
			user_workflowbinary: {},
			user_workqueue: {},
			user_workqueueitem: {},
			workqueueitem_processinguser: {}
		};
		devKit.LoadNavigations(formContext, navigation);
		form.Navigation = navigation;
		form.Utility = devKit.LoadUtility(defaultWebResourceName);
		form.ExecutionContext = devKit.LoadExecutionContext(executionContext);
		devKit.LoadOthers(formContext, form, defaultWebResourceName);
		return form;
	};
	DevKit.FormNguoi_dung_Ung_dung = function(executionContext, defaultWebResourceName) {
		var formContext = null;
		if (executionContext !== undefined) {
			if (executionContext.getFormContext === undefined) {
				formContext = executionContext;
			}
			else {
				formContext = executionContext.getFormContext();
			}
		}
		var form = devKit.LoadForm(formContext);
		var body = {
			ApplicationId: {},
			ApplicationIdUri: {},
			AzureActiveDirectoryObjectId: {},
			DomainName: {},
			FullName: {},
			InternalEMailAddress: {}
		};
		devKit.LoadFields(formContext, body);
		var tab = {
			SUMMARY_TAB: {
				Section: {
					onpremise_account_information: {},
					user_information: {}
				}
			}
		};
		devKit.LoadTabs(formContext, tab);
		body.Tab = tab;
		form.Body = body;
		var navigation = {
			adx_inviteredemption_systemuser_owninguser: {},
			adx_portalcomment_systemuser_owninguser: {},
			adx_webformsession_systemuser: {},
			AIPluginUserSetting_SystemUser_Syst: {},
			bizmap_systemuser_businessid: {},
			contact_owning_user: {},
			email_acceptingentity_systemuser: {},
			flowmachinegroup_PasswordChangedBy: {},
			flowmachinegroup_RotationStartedBy: {},
			knowledgearticle_primaryauthorid: {},
			lk_audit_callinguserid: {},
			lk_audit_userid: {},
			lk_feedback_closedby: {},
			lk_queueitembase_workerid: {},
			lk_teambase_administratorid: {},
			mailbox_regarding_systemuser: {},
			mspp_systemuser_mspp_adplacement_createdby: {},
			mspp_systemuser_mspp_adplacement_modifiedby: {},
			mspp_systemuser_mspp_columnpermission_createdby: {},
			mspp_systemuser_mspp_columnpermission_modifiedby: {},
			mspp_systemuser_mspp_columnpermissionprofile_createdby: {},
			mspp_systemuser_mspp_columnpermissionprofile_modifiedby: {},
			mspp_systemuser_mspp_contentsnippet_createdby: {},
			mspp_systemuser_mspp_contentsnippet_modifiedby: {},
			mspp_systemuser_mspp_entityform_createdby: {},
			mspp_systemuser_mspp_entityform_modifiedby: {},
			mspp_systemuser_mspp_entityformmetadata_createdby: {},
			mspp_systemuser_mspp_entityformmetadata_modifiedby: {},
			mspp_systemuser_mspp_entitylist_createdby: {},
			mspp_systemuser_mspp_entitylist_modifiedby: {},
			mspp_systemuser_mspp_entitypermission_createdby: {},
			mspp_systemuser_mspp_entitypermission_modifiedby: {},
			mspp_systemuser_mspp_pagetemplate_createdby: {},
			mspp_systemuser_mspp_pagetemplate_modifiedby: {},
			mspp_systemuser_mspp_pollplacement_createdby: {},
			mspp_systemuser_mspp_pollplacement_modifiedby: {},
			mspp_systemuser_mspp_publishingstate_createdby: {},
			mspp_systemuser_mspp_publishingstate_modifiedby: {},
			mspp_systemuser_mspp_publishingstatetransitionrule_createdby: {},
			mspp_systemuser_mspp_publishingstatetransitionrule_modifiedby: {},
			mspp_systemuser_mspp_redirect_createdby: {},
			mspp_systemuser_mspp_redirect_modifiedby: {},
			mspp_systemuser_mspp_shortcut_createdby: {},
			mspp_systemuser_mspp_shortcut_modifiedby: {},
			mspp_systemuser_mspp_sitemarker_createdby: {},
			mspp_systemuser_mspp_sitemarker_modifiedby: {},
			mspp_systemuser_mspp_sitesetting_createdby: {},
			mspp_systemuser_mspp_sitesetting_modifiedby: {},
			mspp_systemuser_mspp_webfile_createdby: {},
			mspp_systemuser_mspp_webfile_modifiedby: {},
			mspp_systemuser_mspp_webform_createdby: {},
			mspp_systemuser_mspp_webform_modifiedby: {},
			mspp_systemuser_mspp_webformmetadata_createdby: {},
			mspp_systemuser_mspp_webformmetadata_modifiedby: {},
			mspp_systemuser_mspp_webformstep_createdby: {},
			mspp_systemuser_mspp_webformstep_modifiedby: {},
			mspp_systemuser_mspp_weblink_createdby: {},
			mspp_systemuser_mspp_weblink_modifiedby: {},
			mspp_systemuser_mspp_weblinkset_createdby: {},
			mspp_systemuser_mspp_weblinkset_modifiedby: {},
			mspp_systemuser_mspp_webpage_createdby: {},
			mspp_systemuser_mspp_webpage_modifiedby: {},
			mspp_systemuser_mspp_webpageaccesscontrolrule_createdby: {},
			mspp_systemuser_mspp_webpageaccesscontrolrule_modifiedby: {},
			mspp_systemuser_mspp_webrole_createdby: {},
			mspp_systemuser_mspp_webrole_modifiedby: {},
			mspp_systemuser_mspp_website_createdby: {},
			mspp_systemuser_mspp_website_modifiedby: {},
			mspp_systemuser_mspp_websiteaccess_createdby: {},
			mspp_systemuser_mspp_websiteaccess_modifiedby: {},
			mspp_systemuser_mspp_websitelanguage_createdby: {},
			mspp_systemuser_mspp_websitelanguage_modifiedby: {},
			mspp_systemuser_mspp_webtemplate_createdby: {},
			mspp_systemuser_mspp_webtemplate_modifiedby: {},
			privilegecheckerlog_CheckedUser_systemuser: {},
			privilegecheckerlog_ImpersonatingUser_systemuser: {},
			privilegecheckerlog_SupportingCaller_systemuser: {},
			queue_primary_user: {},
			sideloadedaiplugin_sideloadedpluginownerid: {},
			system_user_accounts: {},
			system_user_contacts: {},
			system_user_email_templates: {},
			system_user_territories: {},
			system_user_workflow: {},
			systemuser_appusersetting_userId: {},
			systemuser_bot_publishedby: {},
			SystemUser_Email_EmailSender: {},
			SystemUser_ExternalPartyItems: {},
			systemuser_internal_addresses: {},
			user_accounts: {},
			user_activityfileattachment: {},
			user_adx_invitation: {},
			user_adx_setting: {},
			user_aiplugin: {},
			user_aipluginauth: {},
			user_aipluginconversationstarter: {},
			user_aipluginconversationstartermapping: {},
			user_aipluginexternalschema: {},
			user_aipluginexternalschemaproperty: {},
			user_aiplugingovernance: {},
			user_aiplugingovernanceext: {},
			user_aiplugininstance: {},
			user_aipluginoperation: {},
			user_aipluginoperationparameter: {},
			user_aipluginoperationresponsetemplate: {},
			user_aipluginusersetting: {},
			user_appnotification: {},
			user_appointment: {},
			user_archivecleanupinfo: {},
			user_archivecleanupoperation: {},
			user_bot: {},
			user_botcomponent: {},
			user_botcomponentcollection: {},
			user_bulkarchiveconfig: {},
			user_bulkarchivefailuredetail: {},
			user_bulkarchiveoperation: {},
			user_canvasappextendedmetadata: {},
			user_card: {},
			user_channelaccessprofile: {},
			user_comment: {},
			user_componentversion: {},
			user_connectioninstance: {},
			user_connectionreference: {},
			user_connector: {},
			user_conversationtranscript: {},
			user_convertrule: {},
			user_copilotglossaryterm: {},
			user_copilotsynonyms: {},
			user_credential: {},
			user_customapi: {},
			user_datalakefolder: {},
			user_desktopflowbinary: {},
			user_desktopflowmodule: {},
			user_dvfilesearch: {},
			user_dvfilesearchattribute: {},
			user_dvfilesearchentity: {},
			user_dvtablesearch: {},
			user_dvtablesearchattribute: {},
			user_dvtablesearchentity: {},
			user_email: {},
			user_enablearchivalrequest: {},
			user_environmentvariabledefinition: {},
			user_environmentvariablevalue: {},
			user_exchangesyncidmapping: {},
			user_exportedexcel: {},
			user_exportsolutionupload: {},
			user_externalparty: {},
			user_fabricaiskill: {},
			user_featurecontrolsetting: {},
			user_federatedknowledgeconfiguration: {},
			user_federatedknowledgeentityconfiguration: {},
			user_flowcapacityassignment: {},
			user_flowcredentialapplication: {},
			user_flowevent: {},
			user_flowmachine: {},
			user_flowmachinegroup: {},
			user_flowmachineimage: {},
			user_flowmachineimageversion: {},
			user_flowmachinenetwork: {},
			user_flowrun: {},
			user_flowsession: {},
			user_fxexpression: {},
			user_goal: {},
			user_goal_goalowner: {},
			user_interactionforemail: {},
			user_keyvaultreference: {},
			user_knowledgearticle: {},
			user_mailbox: {},
			user_managedidentity: {},
			user_msdyn_aibdataset: {},
			user_msdyn_aibdatasetfile: {},
			user_msdyn_aibdatasetrecord: {},
			user_msdyn_aibdatasetscontainer: {},
			user_msdyn_aibfeedbackloop: {},
			user_msdyn_aibfile: {},
			user_msdyn_aibfileattacheddata: {},
			user_msdyn_aievent: {},
			user_msdyn_aifptrainingdocument: {},
			user_msdyn_aimodel: {},
			user_msdyn_aiodimage: {},
			user_msdyn_aiodlabel: {},
			user_msdyn_aiodtrainingboundingbox: {},
			user_msdyn_aiodtrainingimage: {},
			user_msdyn_aitemplate: {},
			user_msdyn_analysiscomponent: {},
			user_msdyn_analysisjob: {},
			user_msdyn_analysisoverride: {},
			user_msdyn_analysisresult: {},
			user_msdyn_analysisresultdetail: {},
			user_msdyn_customcontrolextendedsettings: {},
			user_msdyn_dataflow: {},
			user_msdyn_dataflow_datalakefolder: {},
			user_msdyn_dataflowconnectionreference: {},
			user_msdyn_dataflowrefreshhistory: {},
			user_msdyn_dataflowtemplate: {},
			user_msdyn_dmsrequest: {},
			user_msdyn_dmsrequeststatus: {},
			user_msdyn_dmssyncrequest: {},
			user_msdyn_dmssyncstatus: {},
			user_msdyn_entitylinkchatconfiguration: {},
			user_msdyn_entityrefreshhistory: {},
			user_msdyn_favoriteknowledgearticle: {},
			user_msdyn_federatedarticle: {},
			user_msdyn_fileupload: {},
			user_msdyn_flow_actionapprovalmodel: {},
			user_msdyn_flow_approval: {},
			user_msdyn_flow_approvalrequest: {},
			user_msdyn_flow_approvalresponse: {},
			user_msdyn_flow_approvalstep: {},
			user_msdyn_flow_awaitallactionapprovalmodel: {},
			user_msdyn_flow_awaitallapprovalmodel: {},
			user_msdyn_flow_basicapprovalmodel: {},
			user_msdyn_flow_flowapproval: {},
			user_msdyn_integratedsearchprovider: {},
			user_msdyn_kalanguagesetting: {},
			user_msdyn_kbattachment: {},
			user_msdyn_kmfederatedsearchconfig: {},
			user_msdyn_knowledgearticleimage: {},
			user_msdyn_knowledgearticletemplate: {},
			user_msdyn_knowledgeassetconfiguration: {},
			user_msdyn_knowledgeinteractioninsight: {},
			user_msdyn_knowledgemanagementsetting: {},
			user_msdyn_knowledgepersonalfilter: {},
			user_msdyn_knowledgesearchfilter: {},
			user_msdyn_knowledgesearchinsight: {},
			user_msdyn_mobileapp: {},
			user_msdyn_pmanalysishistory: {},
			user_msdyn_pmbusinessruleautomationconfig: {},
			user_msdyn_pmcalendar: {},
			user_msdyn_pmcalendarversion: {},
			user_msdyn_pminferredtask: {},
			user_msdyn_pmprocessextendedmetadataversion: {},
			user_msdyn_pmprocesstemplate: {},
			user_msdyn_pmprocessusersettings: {},
			user_msdyn_pmprocessversion: {},
			user_msdyn_pmrecording: {},
			user_msdyn_pmsimulation: {},
			user_msdyn_pmtemplate: {},
			user_msdyn_pmview: {},
			user_msdyn_richtextfile: {},
			user_msdyn_salesforcestructuredobject: {},
			user_msdyn_salesforcestructuredqnaconfig: {},
			user_msdyn_schedule: {},
			user_msdyn_serviceconfiguration: {},
			user_msdyn_slakpi: {},
			user_msdyn_solutionhealthrule: {},
			user_msdyn_solutionhealthruleargument: {},
			user_msdyn_virtualtablecolumncandidate: {},
			user_msdynce_botcontent: {},
			user_mspcat_catalogsubmissionfiles: {},
			user_mspcat_packagestore: {},
			user_nlsqregistration: {},
			user_parent_user: {},
			user_pdfsetting: {},
			user_phonecall: {},
			user_plannerbusinessscenario: {},
			user_plannersyncaction: {},
			user_powerbidataset: {},
			user_powerbidatasetapdx: {},
			user_powerbimashupparameter: {},
			user_powerbireport: {},
			user_powerbireportapdx: {},
			user_powerfxrule: {},
			user_powerpagecomponent: {},
			user_powerpagesite: {},
			user_powerpagesitelanguage: {},
			user_powerpagesitepublished: {},
			user_powerpageslog: {},
			user_powerpagesscanreport: {},
			user_privilegecheckerrun: {},
			user_processstageparameter: {},
			user_profilerule: {},
			user_recentlyused: {},
			user_reconciliationentityinfo: {},
			user_reconciliationentitystepinfo: {},
			user_reconciliationinfo: {},
			user_retaineddataexcel: {},
			user_retentioncleanupinfo: {},
			user_retentioncleanupoperation: {},
			user_retentionconfig: {},
			user_retentionfailuredetail: {},
			user_retentionoperation: {},
			user_routingrule: {},
			user_routingruleitem: {},
			user_settings: {},
			user_sharepointsite: {},
			user_sideloadedaiplugin: {},
			user_slabase: {},
			user_solutioncomponentbatchconfiguration: {},
			user_stagesolutionupload: {},
			user_synapsedatabase: {},
			user_task: {},
			user_tdsmetadata: {},
			user_untrackedemail: {},
			user_userauthztracker: {},
			user_workflowbinary: {},
			user_workqueue: {},
			user_workqueueitem: {},
			workqueueitem_processinguser: {}
		};
		devKit.LoadNavigations(formContext, navigation);
		form.Navigation = navigation;
		form.Utility = devKit.LoadUtility(defaultWebResourceName);
		form.ExecutionContext = devKit.LoadExecutionContext(executionContext);
		devKit.LoadOthers(formContext, form, defaultWebResourceName);
		return form;
	};
})(DevKit || (DevKit = {}));
/** @namespace OptionSet */
var OptionSet;
(function (OptionSet) {
	OptionSet.SystemUser = {
		AccessMode : {
			Doc: 2,
			Doc_ghi: 0,
			Khong_tuong_tac: 4,
			Nguoi_dung_ho_tro: 3,
			Quan_tri: 1,
			Quan_tri_vien_dai_dien: 5
		},
		Address1_AddressTypeCode : {
			Gia_tri_mac_dinh: 1
		},
		Address1_ShippingMethodCode : {
			Gia_tri_mac_dinh: 1
		},
		Address2_AddressTypeCode : {
			Gia_tri_mac_dinh: 1
		},
		Address2_ShippingMethodCode : {
			Gia_tri_mac_dinh: 1
		},
		AzureState : {
			Exists: 0,
			Not_found_or_hard_deleted: 2,
			Soft_deleted: 1
		},
		CALType : {
			Ban_hang: 9,
			Chuyen_nghiep: 0,
			Co_ban: 2,
			Dich_vu: 10,
			Doanh_nghiep: 7,
			Field_Service: 11,
			Project_Service: 12,
			Quan_tri: 1,
			Thiet_bi_chuyen_nghiep: 3,
			Thiet_bi_co_ban: 4,
			Thiet_bi_doanh_nghiep: 8,
			Thiet_bi_thiet_yeu: 6,
			Thiet_yeu: 5
		},
		DeletedState : {
			Not_deleted: 0,
			Soft_deleted: 1
		},
		EmailRouterAccessApproval : {
			Bi_tu_choi: 3,
			Da_phe_chuan: 1,
			Dang_cho_Phe_duyet: 2,
			Trong: 0
		},
		IncomingEmailDeliveryMethod : {
			Dong_bo_phia_May_chu_hoac_Bo_dinh_tuyen_Email: 2,
			Hop_thu_chuyen_tiep: 3,
			Khong: 0,
			Microsoft_Dynamics_365_danh_cho_Outlook: 1
		},
		InviteStatusCode : {
			Chua_gui_loi_moi: 0,
			Da_moi: 1,
			Loi_moi_da_chap_nhan: 4,
			Loi_moi_da_het_han: 3,
			Loi_moi_da_thu_hoi: 6,
			Loi_moi_da_tu_choi: 5,
			Loi_moi_gan_het_han: 2
		},
		OutgoingEmailDeliveryMethod : {
			Dong_bo_phia_May_chu_hoac_Bo_dinh_tuyen_Email: 2,
			Khong: 0,
			Microsoft_Dynamics_365_danh_cho_Outlook: 1
		},
		PreferredAddressCode : {
			Dia_chi_khac: 2,
			Dia_chi_thu_tin: 1
		},
		PreferredEmailCode : {
			Gia_tri_mac_dinh: 1
		},
		PreferredPhoneCode : {
			Dien_thoai_Chinh: 1,
			Dien_thoai_Di_dong: 4,
			Dien_thoai_Khac: 2,
			Dien_thoai_Nha_rieng: 3
		},
		RollupState : {
			NotCalculated: 0,
			Calculated: 1,
			OverflowError: 2,
			OtherError: 3,
			RetryLimitExceeded: 4,
			HierarchicalRecursionLimitReached: 5,
			LoopDetected: 6
		}
	};
})(OptionSet || (OptionSet = {}));