'use strict';
/** @namespace DevKit */
var DevKit;
(function (DevKit) {
	'use strict';
	DevKit.FormBieu_mau_nhom_Doanh_nghiep = function(executionContext, defaultWebResourceName) {
		var formContext = null;
		if (executionContext !== undefined) {
			if (executionContext.getFormContext === undefined) {
				formContext = executionContext;
			}
			else {
				formContext = executionContext.getFormContext();
			}
		}
		var form = devKit.LoadForm(formContext);
		var body = {
			AdministratorId: {},
			BusinessUnitId: {},
			Description: {},
			Members: {},
			Name: {},
			TeamType: {}
		};
		devKit.LoadFields(formContext, body);
		var tab = {
			general: {
				Section: {
					Description: {},
					General: {},
					TeamMembers: {}
				}
			}
		};
		devKit.LoadTabs(formContext, tab);
		body.Tab = tab;
		form.Body = body;
		var grid = {
			Members: {},
		};
		devKit.LoadGrids(formContext, grid);
		form.Grid = grid;
		var navigation = {
			adx_inviteredemption_team_owningteam: {},
			adx_portalcomment_team_owningteam: {},
			team_accounts: {},
			team_activityfileattachment: {},
			team_adx_invitation: {},
			team_adx_setting: {},
			team_aiplugin: {},
			team_aipluginauth: {},
			team_aipluginconversationstarter: {},
			team_aipluginconversationstartermapping: {},
			team_aipluginexternalschema: {},
			team_aipluginexternalschemaproperty: {},
			team_aiplugingovernance: {},
			team_aiplugingovernanceext: {},
			team_aiplugininstance: {},
			team_aipluginoperation: {},
			team_aipluginoperationparameter: {},
			team_aipluginoperationresponsetemplate: {},
			team_aipluginusersetting: {},
			team_appnotification: {},
			team_appointment: {},
			team_archivecleanupinfo: {},
			team_archivecleanupoperation: {},
			team_bot: {},
			team_botcomponent: {},
			team_botcomponentcollection: {},
			team_bulkarchiveconfig: {},
			team_bulkarchivefailuredetail: {},
			team_bulkarchiveoperation: {},
			team_canvasappextendedmetadata: {},
			team_card: {},
			team_channelaccessprofile: {},
			team_comment: {},
			team_componentversion: {},
			team_connectioninstance: {},
			team_connectionreference: {},
			team_connector: {},
			team_contacts: {},
			team_conversationtranscript: {},
			team_convertrule: {},
			team_copilotglossaryterm: {},
			team_copilotsynonyms: {},
			team_credential: {},
			team_customapi: {},
			team_datalakefolder: {},
			team_desktopflowbinary: {},
			team_desktopflowmodule: {},
			team_dvfilesearch: {},
			team_dvfilesearchattribute: {},
			team_dvfilesearchentity: {},
			team_dvtablesearch: {},
			team_dvtablesearchattribute: {},
			team_dvtablesearchentity: {},
			team_email: {},
			team_email_templates: {},
			team_emailserverprofile: {},
			team_enablearchivalrequest: {},
			team_environmentvariabledefinition: {},
			team_environmentvariablevalue: {},
			team_exchangesyncidmapping: {},
			team_exportedexcel: {},
			team_exportsolutionupload: {},
			team_externalparty: {},
			team_fabricaiskill: {},
			team_featurecontrolsetting: {},
			team_federatedknowledgeconfiguration: {},
			team_federatedknowledgeentityconfiguration: {},
			team_flowcapacityassignment: {},
			team_flowcredentialapplication: {},
			team_flowevent: {},
			team_flowmachine: {},
			team_flowmachinegroup: {},
			team_flowmachineimage: {},
			team_flowmachineimageversion: {},
			team_flowmachinenetwork: {},
			team_flowrun: {},
			team_flowsession: {},
			team_fxexpression: {},
			team_goal: {},
			team_goal_goalowner: {},
			team_goalrollupquery: {},
			team_interactionforemail: {},
			team_keyvaultreference: {},
			team_knowledgearticle: {},
			team_mailbox: {},
			team_mailboxtrackingcategory: {},
			team_managedidentity: {},
			team_msdyn_aibdataset: {},
			team_msdyn_aibdatasetfile: {},
			team_msdyn_aibdatasetrecord: {},
			team_msdyn_aibdatasetscontainer: {},
			team_msdyn_aibfeedbackloop: {},
			team_msdyn_aibfile: {},
			team_msdyn_aibfileattacheddata: {},
			team_msdyn_aievent: {},
			team_msdyn_aifptrainingdocument: {},
			team_msdyn_aimodel: {},
			team_msdyn_aiodimage: {},
			team_msdyn_aiodlabel: {},
			team_msdyn_aiodtrainingboundingbox: {},
			team_msdyn_aiodtrainingimage: {},
			team_msdyn_aitemplate: {},
			team_msdyn_analysiscomponent: {},
			team_msdyn_analysisjob: {},
			team_msdyn_analysisoverride: {},
			team_msdyn_analysisresult: {},
			team_msdyn_analysisresultdetail: {},
			team_msdyn_customcontrolextendedsettings: {},
			team_msdyn_dataflow: {},
			team_msdyn_dataflow_datalakefolder: {},
			team_msdyn_dataflowconnectionreference: {},
			team_msdyn_dataflowrefreshhistory: {},
			team_msdyn_dataflowtemplate: {},
			team_msdyn_dmsrequest: {},
			team_msdyn_dmsrequeststatus: {},
			team_msdyn_dmssyncrequest: {},
			team_msdyn_dmssyncstatus: {},
			team_msdyn_entitylinkchatconfiguration: {},
			team_msdyn_entityrefreshhistory: {},
			team_msdyn_favoriteknowledgearticle: {},
			team_msdyn_federatedarticle: {},
			team_msdyn_fileupload: {},
			team_msdyn_flow_actionapprovalmodel: {},
			team_msdyn_flow_approval: {},
			team_msdyn_flow_approvalrequest: {},
			team_msdyn_flow_approvalresponse: {},
			team_msdyn_flow_approvalstep: {},
			team_msdyn_flow_awaitallactionapprovalmodel: {},
			team_msdyn_flow_awaitallapprovalmodel: {},
			team_msdyn_flow_basicapprovalmodel: {},
			team_msdyn_flow_flowapproval: {},
			team_msdyn_integratedsearchprovider: {},
			team_msdyn_kalanguagesetting: {},
			team_msdyn_kbattachment: {},
			team_msdyn_kmfederatedsearchconfig: {},
			team_msdyn_knowledgearticleimage: {},
			team_msdyn_knowledgearticletemplate: {},
			team_msdyn_knowledgeassetconfiguration: {},
			team_msdyn_knowledgeinteractioninsight: {},
			team_msdyn_knowledgemanagementsetting: {},
			team_msdyn_knowledgepersonalfilter: {},
			team_msdyn_knowledgesearchfilter: {},
			team_msdyn_knowledgesearchinsight: {},
			team_msdyn_mobileapp: {},
			team_msdyn_pmanalysishistory: {},
			team_msdyn_pmbusinessruleautomationconfig: {},
			team_msdyn_pmcalendar: {},
			team_msdyn_pmcalendarversion: {},
			team_msdyn_pminferredtask: {},
			team_msdyn_pmprocessextendedmetadataversion: {},
			team_msdyn_pmprocesstemplate: {},
			team_msdyn_pmprocessusersettings: {},
			team_msdyn_pmprocessversion: {},
			team_msdyn_pmrecording: {},
			team_msdyn_pmsimulation: {},
			team_msdyn_pmtemplate: {},
			team_msdyn_pmview: {},
			team_msdyn_richtextfile: {},
			team_msdyn_salesforcestructuredobject: {},
			team_msdyn_salesforcestructuredqnaconfig: {},
			team_msdyn_schedule: {},
			team_msdyn_serviceconfiguration: {},
			team_msdyn_slakpi: {},
			team_msdyn_solutionhealthrule: {},
			team_msdyn_solutionhealthruleargument: {},
			team_msdyn_virtualtablecolumncandidate: {},
			team_msdynce_botcontent: {},
			team_mspcat_catalogsubmissionfiles: {},
			team_mspcat_packagestore: {},
			team_nlsqregistration: {},
			team_pdfsetting: {},
			team_phonecall: {},
			team_plannerbusinessscenario: {},
			team_plannersyncaction: {},
			team_powerbidataset: {},
			team_powerbidatasetapdx: {},
			team_powerbimashupparameter: {},
			team_powerbireport: {},
			team_powerbireportapdx: {},
			team_powerfxrule: {},
			team_powerpagecomponent: {},
			team_powerpagesite: {},
			team_powerpagesitelanguage: {},
			team_powerpagesitepublished: {},
			team_powerpageslog: {},
			team_powerpagesscanreport: {},
			team_privilegecheckerrun: {},
			team_processstageparameter: {},
			team_profilerule: {},
			team_queueitembase_workerid: {},
			team_recentlyused: {},
			team_reconciliationentityinfo: {},
			team_reconciliationentitystepinfo: {},
			team_reconciliationinfo: {},
			team_retaineddataexcel: {},
			team_retentioncleanupinfo: {},
			team_retentioncleanupoperation: {},
			team_retentionconfig: {},
			team_retentionfailuredetail: {},
			team_retentionoperation: {},
			team_routingrule: {},
			team_routingruleitem: {},
			team_sharepointsite: {},
			team_sideloadedaiplugin: {},
			team_slaBase: {},
			team_solutioncomponentbatchconfiguration: {},
			team_stagesolutionupload: {},
			team_synapsedatabase: {},
			team_task: {},
			team_tdsmetadata: {},
			team_workflow: {},
			team_workflowbinary: {},
			team_workflowlog: {},
			team_workqueue: {},
			team_workqueueitem: {}
		};
		devKit.LoadNavigations(formContext, navigation);
		form.Navigation = navigation;
		form.Utility = devKit.LoadUtility(defaultWebResourceName);
		form.ExecutionContext = devKit.LoadExecutionContext(executionContext);
		devKit.LoadOthers(formContext, form, defaultWebResourceName);
		return form;
	};
	DevKit.FormTeam = function(executionContext, defaultWebResourceName) {
		var formContext = null;
		if (executionContext !== undefined) {
			if (executionContext.getFormContext === undefined) {
				formContext = executionContext;
			}
			else {
				formContext = executionContext.getFormContext();
			}
		}
		var form = devKit.LoadForm(formContext);
		var body = {
			AdministratorId: {},
			AzureActiveDirectoryObjectId: {},
			BusinessUnitId: {},
			Description: {},
			Members: {},
			MembershipType: {},
			Name: {},
			TeamType: {}
		};
		devKit.LoadFields(formContext, body);
		var tab = {
			general: {
				Section: {
					Description: {},
					General: {},
					TeamMembers: {}
				}
			}
		};
		devKit.LoadTabs(formContext, tab);
		body.Tab = tab;
		form.Body = body;
		var header = {
			QueueId: {}
		};
		devKit.LoadFields(formContext, header, "header_");
		form.Header = header;
		var grid = {
			Members: {},
		};
		devKit.LoadGrids(formContext, grid);
		form.Grid = grid;
		var navigation = {
			adx_inviteredemption_team_owningteam: {},
			adx_portalcomment_team_owningteam: {},
			team_accounts: {},
			team_activityfileattachment: {},
			team_adx_invitation: {},
			team_adx_setting: {},
			team_aiplugin: {},
			team_aipluginauth: {},
			team_aipluginconversationstarter: {},
			team_aipluginconversationstartermapping: {},
			team_aipluginexternalschema: {},
			team_aipluginexternalschemaproperty: {},
			team_aiplugingovernance: {},
			team_aiplugingovernanceext: {},
			team_aiplugininstance: {},
			team_aipluginoperation: {},
			team_aipluginoperationparameter: {},
			team_aipluginoperationresponsetemplate: {},
			team_aipluginusersetting: {},
			team_appnotification: {},
			team_appointment: {},
			team_archivecleanupinfo: {},
			team_archivecleanupoperation: {},
			team_bot: {},
			team_botcomponent: {},
			team_botcomponentcollection: {},
			team_bulkarchiveconfig: {},
			team_bulkarchivefailuredetail: {},
			team_bulkarchiveoperation: {},
			team_canvasappextendedmetadata: {},
			team_card: {},
			team_channelaccessprofile: {},
			team_comment: {},
			team_componentversion: {},
			team_connectioninstance: {},
			team_connectionreference: {},
			team_connector: {},
			team_contacts: {},
			team_conversationtranscript: {},
			team_convertrule: {},
			team_copilotglossaryterm: {},
			team_copilotsynonyms: {},
			team_credential: {},
			team_customapi: {},
			team_datalakefolder: {},
			team_desktopflowbinary: {},
			team_desktopflowmodule: {},
			team_dvfilesearch: {},
			team_dvfilesearchattribute: {},
			team_dvfilesearchentity: {},
			team_dvtablesearch: {},
			team_dvtablesearchattribute: {},
			team_dvtablesearchentity: {},
			team_email: {},
			team_email_templates: {},
			team_emailserverprofile: {},
			team_enablearchivalrequest: {},
			team_environmentvariabledefinition: {},
			team_environmentvariablevalue: {},
			team_exchangesyncidmapping: {},
			team_exportedexcel: {},
			team_exportsolutionupload: {},
			team_externalparty: {},
			team_fabricaiskill: {},
			team_featurecontrolsetting: {},
			team_federatedknowledgeconfiguration: {},
			team_federatedknowledgeentityconfiguration: {},
			team_flowcapacityassignment: {},
			team_flowcredentialapplication: {},
			team_flowevent: {},
			team_flowmachine: {},
			team_flowmachinegroup: {},
			team_flowmachineimage: {},
			team_flowmachineimageversion: {},
			team_flowmachinenetwork: {},
			team_flowrun: {},
			team_flowsession: {},
			team_fxexpression: {},
			team_goal: {},
			team_goal_goalowner: {},
			team_goalrollupquery: {},
			team_interactionforemail: {},
			team_keyvaultreference: {},
			team_knowledgearticle: {},
			team_mailbox: {},
			team_mailboxtrackingcategory: {},
			team_managedidentity: {},
			team_msdyn_aibdataset: {},
			team_msdyn_aibdatasetfile: {},
			team_msdyn_aibdatasetrecord: {},
			team_msdyn_aibdatasetscontainer: {},
			team_msdyn_aibfeedbackloop: {},
			team_msdyn_aibfile: {},
			team_msdyn_aibfileattacheddata: {},
			team_msdyn_aievent: {},
			team_msdyn_aifptrainingdocument: {},
			team_msdyn_aimodel: {},
			team_msdyn_aiodimage: {},
			team_msdyn_aiodlabel: {},
			team_msdyn_aiodtrainingboundingbox: {},
			team_msdyn_aiodtrainingimage: {},
			team_msdyn_aitemplate: {},
			team_msdyn_analysiscomponent: {},
			team_msdyn_analysisjob: {},
			team_msdyn_analysisoverride: {},
			team_msdyn_analysisresult: {},
			team_msdyn_analysisresultdetail: {},
			team_msdyn_customcontrolextendedsettings: {},
			team_msdyn_dataflow: {},
			team_msdyn_dataflow_datalakefolder: {},
			team_msdyn_dataflowconnectionreference: {},
			team_msdyn_dataflowrefreshhistory: {},
			team_msdyn_dataflowtemplate: {},
			team_msdyn_dmsrequest: {},
			team_msdyn_dmsrequeststatus: {},
			team_msdyn_dmssyncrequest: {},
			team_msdyn_dmssyncstatus: {},
			team_msdyn_entitylinkchatconfiguration: {},
			team_msdyn_entityrefreshhistory: {},
			team_msdyn_favoriteknowledgearticle: {},
			team_msdyn_federatedarticle: {},
			team_msdyn_fileupload: {},
			team_msdyn_flow_actionapprovalmodel: {},
			team_msdyn_flow_approval: {},
			team_msdyn_flow_approvalrequest: {},
			team_msdyn_flow_approvalresponse: {},
			team_msdyn_flow_approvalstep: {},
			team_msdyn_flow_awaitallactionapprovalmodel: {},
			team_msdyn_flow_awaitallapprovalmodel: {},
			team_msdyn_flow_basicapprovalmodel: {},
			team_msdyn_flow_flowapproval: {},
			team_msdyn_integratedsearchprovider: {},
			team_msdyn_kalanguagesetting: {},
			team_msdyn_kbattachment: {},
			team_msdyn_kmfederatedsearchconfig: {},
			team_msdyn_knowledgearticleimage: {},
			team_msdyn_knowledgearticletemplate: {},
			team_msdyn_knowledgeassetconfiguration: {},
			team_msdyn_knowledgeinteractioninsight: {},
			team_msdyn_knowledgemanagementsetting: {},
			team_msdyn_knowledgepersonalfilter: {},
			team_msdyn_knowledgesearchfilter: {},
			team_msdyn_knowledgesearchinsight: {},
			team_msdyn_mobileapp: {},
			team_msdyn_pmanalysishistory: {},
			team_msdyn_pmbusinessruleautomationconfig: {},
			team_msdyn_pmcalendar: {},
			team_msdyn_pmcalendarversion: {},
			team_msdyn_pminferredtask: {},
			team_msdyn_pmprocessextendedmetadataversion: {},
			team_msdyn_pmprocesstemplate: {},
			team_msdyn_pmprocessusersettings: {},
			team_msdyn_pmprocessversion: {},
			team_msdyn_pmrecording: {},
			team_msdyn_pmsimulation: {},
			team_msdyn_pmtemplate: {},
			team_msdyn_pmview: {},
			team_msdyn_richtextfile: {},
			team_msdyn_salesforcestructuredobject: {},
			team_msdyn_salesforcestructuredqnaconfig: {},
			team_msdyn_schedule: {},
			team_msdyn_serviceconfiguration: {},
			team_msdyn_slakpi: {},
			team_msdyn_solutionhealthrule: {},
			team_msdyn_solutionhealthruleargument: {},
			team_msdyn_virtualtablecolumncandidate: {},
			team_msdynce_botcontent: {},
			team_mspcat_catalogsubmissionfiles: {},
			team_mspcat_packagestore: {},
			team_nlsqregistration: {},
			team_pdfsetting: {},
			team_phonecall: {},
			team_plannerbusinessscenario: {},
			team_plannersyncaction: {},
			team_powerbidataset: {},
			team_powerbidatasetapdx: {},
			team_powerbimashupparameter: {},
			team_powerbireport: {},
			team_powerbireportapdx: {},
			team_powerfxrule: {},
			team_powerpagecomponent: {},
			team_powerpagesite: {},
			team_powerpagesitelanguage: {},
			team_powerpagesitepublished: {},
			team_powerpageslog: {},
			team_powerpagesscanreport: {},
			team_privilegecheckerrun: {},
			team_processstageparameter: {},
			team_profilerule: {},
			team_queueitembase_workerid: {},
			team_recentlyused: {},
			team_reconciliationentityinfo: {},
			team_reconciliationentitystepinfo: {},
			team_reconciliationinfo: {},
			team_retaineddataexcel: {},
			team_retentioncleanupinfo: {},
			team_retentioncleanupoperation: {},
			team_retentionconfig: {},
			team_retentionfailuredetail: {},
			team_retentionoperation: {},
			team_routingrule: {},
			team_routingruleitem: {},
			team_sharepointsite: {},
			team_sideloadedaiplugin: {},
			team_slaBase: {},
			team_solutioncomponentbatchconfiguration: {},
			team_stagesolutionupload: {},
			team_synapsedatabase: {},
			team_task: {},
			team_tdsmetadata: {},
			team_workflow: {},
			team_workflowbinary: {},
			team_workflowlog: {},
			team_workqueue: {},
			team_workqueueitem: {}
		};
		devKit.LoadNavigations(formContext, navigation);
		form.Navigation = navigation;
		form.Utility = devKit.LoadUtility(defaultWebResourceName);
		form.ExecutionContext = devKit.LoadExecutionContext(executionContext);
		devKit.LoadOthers(formContext, form, defaultWebResourceName);
		return form;
	};
})(DevKit || (DevKit = {}));
/** @namespace OptionSet */
var OptionSet;
(function (OptionSet) {
	OptionSet.Team = {
		MembershipType : {
			Guests: 3,
			Members: 1,
			Members_and_guests: 0,
			Owners: 2
		},
		RegardingObjectTypeCode : {
		},
		TeamType : {
			Chu_so_huu: 0,
			Nhom_bao_mat_AAD: 2,
			Nhom_Office_AAD: 3,
			Truy_cap: 1
		},
		RollupState : {
			NotCalculated: 0,
			Calculated: 1,
			OverflowError: 2,
			OtherError: 3,
			RetryLimitExceeded: 4,
			HierarchicalRecursionLimitReached: 5,
			LoopDetected: 6
		}
	};
})(OptionSet || (OptionSet = {}));