<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RuntimeIdentifier>win</RuntimeIdentifier>
		<Nullable>disable</Nullable>
		<LangVersion>latest</LangVersion>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
		<PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="EnvDTE80" Version="8.0.3" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="WindowsBase" />
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="System.Xaml" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\DynamicsCrm.DevKit.2019\DynamicsCrm.DevKit.2019.csproj" />
	</ItemGroup>
</Project>
