#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.DevKit.ProxyTypes
{
	
	
	/// <summary>
	/// Chỉ sử dụng nội bộ.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum documentindex_documenttypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Gitrmcnh = 1,
	}
	
	/// <summary>
	/// Bài viết được lập chỉ mục phục vụ mục đích tìm kiếm.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("documentindex")]
	public partial class DocumentIndex : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the documentindex entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string DocumentId = "documentid";
			public const string DocumentIndexId = "documentindexid";
			public const string Id = "documentindexid";
			public const string DocumentTypeCode = "documenttypecode";
			public const string DocumentTypeCodeName = "documenttypecodename";
			public const string IsLatestVersion = "islatestversion";
			public const string IsLatestVersionName = "islatestversionname";
			public const string IsPublished = "ispublished";
			public const string IsPublishedName = "ispublishedname";
			public const string KeyWords = "keywords";
			public const string Location = "location";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Number = "number";
			public const string OrganizationId = "organizationid";
			public const string SearchText = "searchtext";
			public const string SubjectId = "subjectid";
			public const string Title = "title";
			public const string VersionNumber = "versionnumber";
			public const string userentityinstancedata_documentindex = "userentityinstancedata_documentindex";
			public const string is_primary_subject_for = "is_primary_subject_for";
			public const string KbArticle_DocumentIndex = "KbArticle_DocumentIndex";
			public const string knowledgearticle_documentindex = "knowledgearticle_documentindex";
			public const string lk_documentindex_createdby = "lk_documentindex_createdby";
			public const string lk_documentindex_createdonbehalfby = "lk_documentindex_createdonbehalfby";
			public const string lk_documentindex_modifiedby = "lk_documentindex_modifiedby";
			public const string lk_documentindex_modifiedonbehalfby = "lk_documentindex_modifiedonbehalfby";
			public const string organization_indexed_documents = "organization_indexed_documents";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public DocumentIndex() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "documentindex";
		
		public const string EntityLogicalCollectionName = "documentindexes";
		
		public const string EntitySetName = "documentindexes";
		
		public const int EntityTypeCode = 126;
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng đã tạo bài biết được lập chỉ mục.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Ngày và giờ tạo bài viết được lập chỉ mục.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng đại diện đã tạo documentindex.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Chọn bài biết ở cấp độ cha cho mục chỉ mục tài liệu. ID liên kết chỉ mục với thông tin bài viết chẳng hạn như số, tiêu đề và từ khóa của bài viết.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentid")]
		public Microsoft.Xrm.Sdk.EntityReference DocumentId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("documentid");
			}
			set
			{
				this.SetAttributeValue("documentid", value);
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của bài viết được lập chỉ mục.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentindexid")]
		public System.Nullable<System.Guid> DocumentIndexId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("documentindexid");
			}
			set
			{
				this.SetAttributeValue("documentindexid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentindexid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.DocumentIndexId = value;
			}
		}
		
		/// <summary>
		/// Chỉ sử dụng nội bộ.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documenttypecode")]
		public virtual documentindex_documenttypecode? DocumentTypeCode
		{
			get
			{
				return ((documentindex_documenttypecode?)(EntityOptionSetEnum.GetEnum(this, "documenttypecode")));
			}
			set
			{
				this.SetAttributeValue("documenttypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documenttypecodename")]
		public string DocumentTypeCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("documenttypecode"))
				{
					return this.FormattedValues["documenttypecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Cho biết phiên bản nào của bài viết trong cơ sở kiến thức là phiên bản mới nhất.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("islatestversion")]
		public System.Nullable<bool> IsLatestVersion
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("islatestversion");
			}
			set
			{
				this.SetAttributeValue("islatestversion", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("islatestversionname")]
		public string IsLatestVersionName
		{
			get
			{
				if (this.FormattedValues.Contains("islatestversion"))
				{
					return this.FormattedValues["islatestversion"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Cho biết bài viết trong cơ sở kiến thức ở cấp độ cha có hay không được phát hành trong Microsoft Dynamics 365 để từ khóa và nội dung bài viết được bổ sung vào chỉ mục tìm kiếm.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispublished")]
		public System.Nullable<bool> IsPublished
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ispublished");
			}
			set
			{
				this.SetAttributeValue("ispublished", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispublishedname")]
		public string IsPublishedName
		{
			get
			{
				if (this.FormattedValues.Contains("ispublished"))
				{
					return this.FormattedValues["ispublished"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Nhập từ khóa cho bài viết. Từ khóa được cập nhật trong chỉ mục tìm kiếm mỗi lần phát hành bài viết.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keywords")]
		public string KeyWords
		{
			get
			{
				return this.GetAttributeValue<string>("keywords");
			}
			set
			{
				this.SetAttributeValue("keywords", value);
			}
		}
		
		/// <summary>
		/// Chỉ sử dụng trong hệ thống.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("location")]
		public string Location
		{
			get
			{
				return this.GetAttributeValue<string>("location");
			}
			set
			{
				this.SetAttributeValue("location", value);
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng sửa đổi bài viết được lập chỉ mục lần cuối.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Ngày và giờ sửa đổi bài viết được lập chỉ mục lần cuối.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng đại diện đã sửa đổi documentindex lần cuối.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Chỉ sử dụng nội bộ.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("number")]
		public string Number
		{
			get
			{
				return this.GetAttributeValue<string>("number");
			}
			set
			{
				this.SetAttributeValue("number", value);
			}
		}
		
		/// <summary>
		/// Chọn ID của tổ chức có bản ghi được liên kết.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Chỉ sử dụng nội bộ.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("searchtext")]
		public string SearchText
		{
			get
			{
				return this.GetAttributeValue<string>("searchtext");
			}
			set
			{
				this.SetAttributeValue("searchtext", value);
			}
		}
		
		/// <summary>
		/// Cho biết bản ghi chủ đề được chọn trong bài viết ở cấp độ cha của cơ sở kiến thức. ID được cập nhật trong chỉ mục tìm kiếm mỗi lần phát hành bài viết.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
		public Microsoft.Xrm.Sdk.EntityReference SubjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("subjectid");
			}
			set
			{
				this.SetAttributeValue("subjectid", value);
			}
		}
		
		/// <summary>
		/// Nhập tiêu đề của bài viết trong cơ sở kiến thức ở cấp độ cha. Dữ liệu này được cập nhật trong chỉ mục tìm kiếm mỗi lần phát hành bài viết.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			set
			{
				this.SetAttributeValue("title", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N userentityinstancedata_documentindex
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_documentindex")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.UserEntityInstanceData> userentityinstancedata_documentindex
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.UserEntityInstanceData>("userentityinstancedata_documentindex", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.UserEntityInstanceData>("userentityinstancedata_documentindex", null, value);
			}
		}
		
		/// <summary>
		/// N:1 is_primary_subject_for
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("is_primary_subject_for")]
		public Dev.DevKit.ProxyTypes.Subject is_primary_subject_for
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.Subject>("is_primary_subject_for", null);
			}
			set
			{
				this.SetRelatedEntity<Dev.DevKit.ProxyTypes.Subject>("is_primary_subject_for", null, value);
			}
		}
		
		/// <summary>
		/// N:1 KbArticle_DocumentIndex
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KbArticle_DocumentIndex")]
		public Dev.DevKit.ProxyTypes.KbArticle KbArticle_DocumentIndex
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.KbArticle>("KbArticle_DocumentIndex", null);
			}
			set
			{
				this.SetRelatedEntity<Dev.DevKit.ProxyTypes.KbArticle>("KbArticle_DocumentIndex", null, value);
			}
		}
		
		/// <summary>
		/// N:1 knowledgearticle_documentindex
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_documentindex")]
		public Dev.DevKit.ProxyTypes.KnowledgeArticle knowledgearticle_documentindex
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.KnowledgeArticle>("knowledgearticle_documentindex", null);
			}
			set
			{
				this.SetRelatedEntity<Dev.DevKit.ProxyTypes.KnowledgeArticle>("knowledgearticle_documentindex", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_documentindex_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_documentindex_createdby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_documentindex_createdby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_documentindex_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_documentindex_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_documentindex_createdonbehalfby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_documentindex_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_documentindex_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_documentindex_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_documentindex_modifiedby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_documentindex_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_documentindex_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_documentindex_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_documentindex_modifiedonbehalfby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_documentindex_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_documentindex_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 organization_indexed_documents
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_indexed_documents")]
		public Dev.DevKit.ProxyTypes.Organization organization_indexed_documents
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.Organization>("organization_indexed_documents", null);
			}
		}
	}
}
#pragma warning restore CS1591
