#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.DevKit.ProxyTypes
{
	
	
	/// <summary>
	/// Status of the Knowledge Interaction Insight
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_knowledgeinteractioninsight_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Knowledge Interaction Insight
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_knowledgeinteractioninsight_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Knowledge Interaction Insight
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_knowledgeinteractioninsight")]
	public partial class msdyn_knowledgeinteractioninsight : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the msdyn_knowledgeinteractioninsight entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string msdyn_ArticleRank = "msdyn_articlerank";
			public const string msdyn_ArticleRecordId = "msdyn_articlerecordid";
			public const string msdyn_ArticleRelevance = "msdyn_articlerelevance";
			public const string msdyn_InteractionContext = "msdyn_interactioncontext";
			public const string msdyn_InteractionType = "msdyn_interactiontype";
			public const string msdyn_knowledgeinteractioninsightId = "msdyn_knowledgeinteractioninsightid";
			public const string Id = "msdyn_knowledgeinteractioninsightid";
			public const string msdyn_KnowledgeOperationId = "msdyn_knowledgeoperationid";
			public const string msdyn_KnowledgeOperationType = "msdyn_knowledgeoperationtype";
			public const string msdyn_TimeStamp = "msdyn_timestamp";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string msdyn_knowledgeinteractioninsight_AsyncOperations = "msdyn_knowledgeinteractioninsight_AsyncOperations";
			public const string msdyn_knowledgeinteractioninsight_BulkDeleteFailures = "msdyn_knowledgeinteractioninsight_BulkDeleteFailures";
			public const string msdyn_knowledgeinteractioninsight_DuplicateBaseRecord = "msdyn_knowledgeinteractioninsight_DuplicateBaseRecord";
			public const string msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord = "msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord";
			public const string msdyn_knowledgeinteractioninsight_MailboxTrackingFolders = "msdyn_knowledgeinteractioninsight_MailboxTrackingFolders";
			public const string msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses = "msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses";
			public const string msdyn_knowledgeinteractioninsight_ProcessSession = "msdyn_knowledgeinteractioninsight_ProcessSession";
			public const string msdyn_knowledgeinteractioninsight_SyncErrors = "msdyn_knowledgeinteractioninsight_SyncErrors";
			public const string msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas = "msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas";
			public const string business_unit_msdyn_knowledgeinteractioninsight = "business_unit_msdyn_knowledgeinteractioninsight";
			public const string lk_msdyn_knowledgeinteractioninsight_createdby = "lk_msdyn_knowledgeinteractioninsight_createdby";
			public const string lk_msdyn_knowledgeinteractioninsight_createdonbehalfby = "lk_msdyn_knowledgeinteractioninsight_createdonbehalfby";
			public const string lk_msdyn_knowledgeinteractioninsight_modifiedby = "lk_msdyn_knowledgeinteractioninsight_modifiedby";
			public const string lk_msdyn_knowledgeinteractioninsight_modifiedonbehalfby = "lk_msdyn_knowledgeinteractioninsight_modifiedonbehalfby";
			public const string team_msdyn_knowledgeinteractioninsight = "team_msdyn_knowledgeinteractioninsight";
			public const string user_msdyn_knowledgeinteractioninsight = "user_msdyn_knowledgeinteractioninsight";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msdyn_knowledgeinteractioninsight() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_knowledgeinteractioninsight";
		
		public const string EntityLogicalCollectionName = "msdyn_knowledgeinteractioninsights";
		
		public const string EntitySetName = "msdyn_knowledgeinteractioninsights";
		
		public const int EntityTypeCode = 10195;
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The position of the article in the returned article list
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_articlerank")]
		public System.Nullable<int> msdyn_ArticleRank
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_articlerank");
			}
			set
			{
				this.SetAttributeValue("msdyn_articlerank", value);
			}
		}
		
		/// <summary>
		/// The ID of the knowledge article record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_articlerecordid")]
		public string msdyn_ArticleRecordId
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_articlerecordid");
			}
			set
			{
				this.SetAttributeValue("msdyn_articlerecordid", value);
			}
		}
		
		/// <summary>
		/// Relevance score for the knowledge article returned by the search engine
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_articlerelevance")]
		public System.Nullable<double> msdyn_ArticleRelevance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_articlerelevance");
			}
			set
			{
				this.SetAttributeValue("msdyn_articlerelevance", value);
			}
		}
		
		/// <summary>
		/// Context of custom interactions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_interactioncontext")]
		public string msdyn_InteractionContext
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_interactioncontext");
			}
			set
			{
				this.SetAttributeValue("msdyn_interactioncontext", value);
			}
		}
		
		/// <summary>
		/// The type of interaction with the customer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_interactiontype")]
		public string msdyn_InteractionType
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_interactiontype");
			}
			set
			{
				this.SetAttributeValue("msdyn_interactiontype", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_knowledgeinteractioninsightid")]
		public System.Nullable<System.Guid> msdyn_knowledgeinteractioninsightId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_knowledgeinteractioninsightid");
			}
			set
			{
				this.SetAttributeValue("msdyn_knowledgeinteractioninsightid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_knowledgeinteractioninsightid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.msdyn_knowledgeinteractioninsightId = value;
			}
		}
		
		/// <summary>
		/// The related Record ID of the knowledge operation entity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_knowledgeoperationid")]
		public string msdyn_KnowledgeOperationId
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_knowledgeoperationid");
			}
			set
			{
				this.SetAttributeValue("msdyn_knowledgeoperationid", value);
			}
		}
		
		/// <summary>
		/// The operation type performed, such as search or recommendation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_knowledgeoperationtype")]
		public string msdyn_KnowledgeOperationType
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_knowledgeoperationtype");
			}
			set
			{
				this.SetAttributeValue("msdyn_knowledgeoperationtype", value);
			}
		}
		
		/// <summary>
		/// Date and time of the interaction.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_timestamp")]
		public System.Nullable<System.DateTime> msdyn_TimeStamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_timestamp");
			}
			set
			{
				this.SetAttributeValue("msdyn_timestamp", value);
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Knowledge Interaction Insight
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual msdyn_knowledgeinteractioninsight_statecode? statecode
		{
			get
			{
				return ((msdyn_knowledgeinteractioninsight_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Knowledge Interaction Insight
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msdyn_knowledgeinteractioninsight_statuscode? statuscode
		{
			get
			{
				return ((msdyn_knowledgeinteractioninsight_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.AsyncOperation> msdyn_knowledgeinteractioninsight_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.AsyncOperation>("msdyn_knowledgeinteractioninsight_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.AsyncOperation>("msdyn_knowledgeinteractioninsight_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.BulkDeleteFailure> msdyn_knowledgeinteractioninsight_BulkDeleteFailures
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.BulkDeleteFailure>("msdyn_knowledgeinteractioninsight_BulkDeleteFailures", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.BulkDeleteFailure>("msdyn_knowledgeinteractioninsight_BulkDeleteFailures", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.DuplicateRecord> msdyn_knowledgeinteractioninsight_DuplicateBaseRecord
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.DuplicateRecord>("msdyn_knowledgeinteractioninsight_DuplicateBaseRecord", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.DuplicateRecord>("msdyn_knowledgeinteractioninsight_DuplicateBaseRecord", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.DuplicateRecord> msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.DuplicateRecord>("msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.DuplicateRecord>("msdyn_knowledgeinteractioninsight_DuplicateMatchingRecord", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.MailboxTrackingFolder> msdyn_knowledgeinteractioninsight_MailboxTrackingFolders
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.MailboxTrackingFolder>("msdyn_knowledgeinteractioninsight_MailboxTrackingFolders", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.MailboxTrackingFolder>("msdyn_knowledgeinteractioninsight_MailboxTrackingFolders", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.PrincipalObjectAttributeAccess> msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.PrincipalObjectAttributeAccess>("msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.PrincipalObjectAttributeAccess>("msdyn_knowledgeinteractioninsight_PrincipalObjectAttributeAccesses", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_ProcessSession")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.ProcessSession> msdyn_knowledgeinteractioninsight_ProcessSession
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.ProcessSession>("msdyn_knowledgeinteractioninsight_ProcessSession", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.ProcessSession>("msdyn_knowledgeinteractioninsight_ProcessSession", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_SyncErrors")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.SyncError> msdyn_knowledgeinteractioninsight_SyncErrors
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.SyncError>("msdyn_knowledgeinteractioninsight_SyncErrors", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.SyncError>("msdyn_knowledgeinteractioninsight_SyncErrors", null, value);
			}
		}
		
		/// <summary>
		/// 1:N msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<Dev.DevKit.ProxyTypes.UserEntityInstanceData> msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas
		{
			get
			{
				return this.GetRelatedEntities<Dev.DevKit.ProxyTypes.UserEntityInstanceData>("msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas", null);
			}
			set
			{
				this.SetRelatedEntities<Dev.DevKit.ProxyTypes.UserEntityInstanceData>("msdyn_knowledgeinteractioninsight_UserEntityInstanceDatas", null, value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_msdyn_knowledgeinteractioninsight
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_knowledgeinteractioninsight")]
		public Dev.DevKit.ProxyTypes.BusinessUnit business_unit_msdyn_knowledgeinteractioninsight
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.BusinessUnit>("business_unit_msdyn_knowledgeinteractioninsight", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_knowledgeinteractioninsight_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_knowledgeinteractioninsight_createdby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_msdyn_knowledgeinteractioninsight_createdby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_msdyn_knowledgeinteractioninsight_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_knowledgeinteractioninsight_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_knowledgeinteractioninsight_createdonbehalfby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_msdyn_knowledgeinteractioninsight_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_msdyn_knowledgeinteractioninsight_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_knowledgeinteractioninsight_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_knowledgeinteractioninsight_modifiedby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_msdyn_knowledgeinteractioninsight_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_msdyn_knowledgeinteractioninsight_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_knowledgeinteractioninsight_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_knowledgeinteractioninsight_modifiedonbehalfby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_msdyn_knowledgeinteractioninsight_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_msdyn_knowledgeinteractioninsight_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 team_msdyn_knowledgeinteractioninsight
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_knowledgeinteractioninsight")]
		public Dev.DevKit.ProxyTypes.Team team_msdyn_knowledgeinteractioninsight
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.Team>("team_msdyn_knowledgeinteractioninsight", null);
			}
		}
		
		/// <summary>
		/// N:1 user_msdyn_knowledgeinteractioninsight
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_knowledgeinteractioninsight")]
		public Dev.DevKit.ProxyTypes.SystemUser user_msdyn_knowledgeinteractioninsight
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("user_msdyn_knowledgeinteractioninsight", null);
			}
		}
	}
}
#pragma warning restore CS1591
