#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.DevKit.ProxyTypes
{
	
	
	/// <summary>
	/// Dùng để lưu trữ Tài liệu Office trong cơ sở dữ liệu ở định dạng nhị phân.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("officedocument")]
	public partial class OfficeDocument : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the officedocument entity
		/// </summary>
		public partial class Fields
		{
			public const string ClientData = "clientdata";
			public const string Content = "content";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string DocumentType = "documenttype";
			public const string DocumentTypeName = "documenttypename";
			public const string FileLockState = "filelockstate";
			public const string FileSize = "filesize";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string ObjectId = "objectid";
			public const string OfficeDocumentId = "officedocumentid";
			public const string Id = "officedocumentid";
			public const string OwnerId = "ownerid";
			public const string SHA256 = "sha256";
			public const string VersionNumber = "versionnumber";
			public const string lk_officedocumentbase_createdonbehalfby = "lk_officedocumentbase_createdonbehalfby";
			public const string lk_officedocumentbase_modifiedonbehalfby = "lk_officedocumentbase_modifiedonbehalfby";
			public const string owner_officedocument = "owner_officedocument";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public OfficeDocument() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "officedocument";
		
		public const string EntityLogicalCollectionName = "officedocuments";
		
		public const string EntitySetName = "officedocuments";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Dữ liệu máy khách về tài liệu Office này.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientdata")]
		public string ClientData
		{
			get
			{
				return this.GetAttributeValue<string>("clientdata");
			}
			set
			{
				this.OnPropertyChanging("ClientData");
				this.SetAttributeValue("clientdata", value);
				this.OnPropertyChanged("ClientData");
			}
		}
		
		/// <summary>
		/// Số byte của tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("content")]
		public string Content
		{
			get
			{
				return this.GetAttributeValue<string>("content");
			}
			set
			{
				this.OnPropertyChanging("Content");
				this.SetAttributeValue("content", value);
				this.OnPropertyChanged("Content");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng đã tạo tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Ngày và giờ tạo tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng đại diện đã tạo tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Bộ tùy chọn để chọn loại tài liệu Office
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documenttype")]
		public virtual officedocument_documenttype? DocumentType
		{
			get
			{
				return ((officedocument_documenttype?)(EntityOptionSetEnum.GetEnum(this, "documenttype")));
			}
			set
			{
				this.OnPropertyChanging("DocumentType");
				this.SetAttributeValue("documenttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("DocumentType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documenttypename")]
		public string DocumentTypeName
		{
			get
			{
				if (this.FormattedValues.Contains("documenttype"))
				{
					return this.FormattedValues["documenttype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Trạng thái khóa tệp.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filelockstate")]
		public System.Nullable<int> FileLockState
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("filelockstate");
			}
			set
			{
				this.OnPropertyChanging("FileLockState");
				this.SetAttributeValue("filelockstate", value);
				this.OnPropertyChanged("FileLockState");
			}
		}
		
		/// <summary>
		/// Kích thước Tệp.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filesize")]
		public System.Nullable<int> FileSize
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("filesize");
			}
			set
			{
				this.OnPropertyChanging("FileSize");
				this.SetAttributeValue("filesize", value);
				this.OnPropertyChanged("FileSize");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng sửa đổi tài liệu Office lần cuối.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Ngày và giờ sửa đổi tài liệu Office lần cuối.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng đại diện đã sửa đổi tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Tên của tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Id Đối tượng.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public Microsoft.Xrm.Sdk.EntityReference ObjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("objectid");
			}
			set
			{
				this.OnPropertyChanging("ObjectId");
				this.SetAttributeValue("objectid", value);
				this.OnPropertyChanged("ObjectId");
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("officedocumentid")]
		public System.Nullable<System.Guid> OfficeDocumentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("officedocumentid");
			}
			set
			{
				this.OnPropertyChanging("OfficeDocumentId");
				this.SetAttributeValue("officedocumentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("OfficeDocumentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("officedocumentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.OfficeDocumentId = value;
			}
		}
		
		/// <summary>
		/// Mã định danh duy nhất của người dùng hoặc nhóm sở hữu tài liệu Office.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Lưu trữ giá trị khóa Hàm băm SHA256.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sha256")]
		public string SHA256
		{
			get
			{
				return this.GetAttributeValue<string>("sha256");
			}
			set
			{
				this.OnPropertyChanging("SHA256");
				this.SetAttributeValue("sha256", value);
				this.OnPropertyChanged("SHA256");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 lk_officedocumentbase_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_officedocumentbase_createdonbehalfby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_officedocumentbase_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_officedocumentbase_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_officedocumentbase_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_officedocumentbase_modifiedonbehalfby")]
		public Dev.DevKit.ProxyTypes.SystemUser lk_officedocumentbase_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.SystemUser>("lk_officedocumentbase_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 owner_officedocument
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_officedocument")]
		public Dev.DevKit.ProxyTypes.Owner owner_officedocument
		{
			get
			{
				return this.GetRelatedEntity<Dev.DevKit.ProxyTypes.Owner>("owner_officedocument", null);
			}
			set
			{
				this.OnPropertyChanging("owner_officedocument");
				this.SetRelatedEntity<Dev.DevKit.ProxyTypes.Owner>("owner_officedocument", null, value);
				this.OnPropertyChanged("owner_officedocument");
			}
		}
	}
}
#pragma warning restore CS1591
