#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.DevKit.ProxyTypes
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("QuickTest")]
	public partial class QuickTestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string version
		{
			get
			{
				if (this.Parameters.Contains("version"))
				{
					return ((string)(this.Parameters["version"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["version"] = value;
			}
		}
		
		public string request
		{
			get
			{
				if (this.Parameters.Contains("request"))
				{
					return ((string)(this.Parameters["request"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["request"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity requestv2
		{
			get
			{
				if (this.Parameters.Contains("requestv2"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["requestv2"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["requestv2"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string source
		{
			get
			{
				if (this.Parameters.Contains("source"))
				{
					return ((string)(this.Parameters["source"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["source"] = value;
			}
		}
		
		public QuickTestRequest()
		{
			this.RequestName = "QuickTest";
			this.version = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("QuickTest")]
	public partial class QuickTestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public QuickTestResponse()
		{
		}
		
		public string overrideHttpStatusCode
		{
			get
			{
				if (this.Results.Contains("overrideHttpStatusCode"))
				{
					return ((string)(this.Results["overrideHttpStatusCode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string overrideLocation
		{
			get
			{
				if (this.Results.Contains("overrideLocation"))
				{
					return ((string)(this.Results["overrideLocation"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string overrideRetryAfter
		{
			get
			{
				if (this.Results.Contains("overrideRetryAfter"))
				{
					return ((string)(this.Results["overrideRetryAfter"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity responsev2
		{
			get
			{
				if (this.Results.Contains("responsev2"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["responsev2"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
	}
}
#pragma warning restore CS1591
